import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {transformWithOxc} from 'vite';
import {adminGroups, adminCounters} from '../../src/components/adminDashboard.mjs';
const source=readFileSync('src/components/AdminWorkspace.jsx','utf8');
const css=readFileSync('src/components/AdminWorkspace.css','utf8');
const app=readFileSync('src/App.jsx','utf8');
const {code}=await transformWithOxc('import React from "react";\n'+source.replace("import './AdminWorkspace.css';",''),'AdminWorkspace.jsx',{jsx:{runtime:'classic'}});
const compiled=code.replaceAll('from "react"',`from "${import.meta.resolve('react')}"`).replace(/from ["']\.\/adminDashboard\.mjs["']/g,`from "${new URL('../../src/components/adminDashboard.mjs',import.meta.url)}"`);
const {default:Workspace}=await import('data:text/javascript;base64,'+Buffer.from(compiled).toString('base64'));
const ids=adminGroups.flatMap(g=>g.ids);
const data={pendingEvents:[{}],pendingBusinesses:[{},{}],pendingClaims:[],pendingGalleryPhotos:[{}],pendingReviews:[],adminMarketplaceListings:[{moderation_status:'pending'},{moderation_status:'approved'}],adminJobListings:[{status:'pending'},{status:'approved'}],adminRentalListings:[{status:'hidden'}]};
const props={enabled:true,authorized:true,tabs:ids.filter(id=>id!=='dashboard').map(id=>({id,label:id})),selected:'dashboard',counts:adminCounters(data),summaries:[{label:'Published businesses',value:7,module:'businesses'}],status:'ready'};
const render=overrides=>renderToStaticMarkup(React.createElement(Workspace,{...props,...overrides},React.createElement('p',null,'Existing module content')));
test('all ten existing modules remain independent navigation entries',()=>{assert.equal(new Set(ids).size,11);for(const id of ids)assert.match(render(),new RegExp(`>${id}<`,'i'));});
test('dashboard counters use loaded queues and pending statuses only',()=>{assert.deepEqual(adminCounters(data),{events:1,businesses:2,claims:0,gallery:1,reviews:0,marketplace:1,jobs:1,rentals:0});assert.equal(data.pendingBusinesses.length,2);});
test('camel-case marketplace state supported without counting approved rows',()=>{assert.equal(adminCounters({...data,adminMarketplaceListings:[{moderationStatus:'pending'},{moderationStatus:'approved'}]}).marketplace,1);});
test('dashboard displays real zero counts and loaded published summary',()=>{assert.match(render(),/<strong>0<\/strong>/);assert.match(render(),/<strong>7<\/strong>/);});
test('loading dashboard never presents unloaded numbers as zero',()=>{const html=render({status:'loading'});assert.match(html,/Loading data/);assert.doesNotMatch(html,/<strong>[0-9]+<\/strong>/);});
for(const selected of ids.slice(1))test(`navigation selects ${selected} independently`,()=>{const html=render({selected});assert.match(html,new RegExp(`<h1[^>]*>${selected}<`));assert.equal((html.match(/aria-current="page"/g)||[]).length,1);assert.doesNotMatch(html,/Dashboard overview/);assert.match(html,/Existing module content/);});
test('unauthorized workspace exposes no sidebar or dashboard',()=>{const html=render({authorized:false});assert.doesNotMatch(html,/Admin modules|Dashboard overview|Sign Out/);assert.match(html,/Back to Lobby/);});
test('native admin remains original child content',()=>{assert.equal(render({enabled:false}),'<p>Existing module content</p>');});
test('drawer is a real button with linked accessible navigation',()=>{assert.match(render(),/aria-label="Open navigation" aria-expanded="false" aria-controls="admin-navigation"/);assert.match(source,/role=\{open\?'dialog'/);assert.match(source,/event.key==='Escape'/);assert.match(source,/event.key==='Tab'/);assert.match(source,/setOpen\(false\);requestAnimationFrame/);});
test('responsive CSS uses drawer and one-column mobile surfaces',()=>{assert.match(css,/@media \(max-width:999px\)/);assert.match(css,/\.drawer-open \.aw-sidebar \{display:flex/);assert.match(css,/@media \(max-width:600px\)/);assert.match(css,/min-height:44px/);assert.match(css,/focus-visible/);});
test('web defaults to Dashboard and keeps native Events initial view',()=>{assert.match(app,/useState\(adminWeb \? "dashboard" : "events"\)/);assert.match(app,/adminWeb && \(afterMutation \|\| !showRefreshSuccess\)/);});
test('COMP and claim contracts retained; no commercial direct update introduced',()=>{for(const rpc of ['grant_admin_comp','revoke_admin_comp','review_business_claim','moderate_premium_event'])assert.ok(app.includes(`rpc("${rpc}"`));assert.match(app,/Admin Promo \/ COMP/);assert.match(app,/Business: \{/);});
