import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {transformWithOxc} from 'vite';
import {adminDate,adminBadgeText} from '../../src/components/adminPresentation.mjs';
const app=readFileSync('src/App.jsx','utf8'),css=readFileSync('src/components/AdminWorkspace.css','utf8');
const source=readFileSync('src/components/AdminCardMedia.jsx','utf8');
const {code}=await transformWithOxc('import React from "react";\n'+source,'AdminCardMedia.jsx',{jsx:{runtime:'classic'}});
const {default:Media}=await import('data:text/javascript;base64,'+Buffer.from(code.replaceAll('from "react"',`from "${import.meta.resolve('react')}"`)).toString('base64'));
test('Jobs uses the same image_data source as the public job mapping',()=>{assert.match(app,/image: row.image_data/);assert.match(app,/<AdminCardMedia src=\{job.image_data\}/);});
test('image source renders responsive media; absent source creates no broken img',()=>{assert.match(renderToStaticMarkup(React.createElement(Media,{src:'https://example.invalid/synthetic.png'})),/class="aw-card-media"/);for(const src of [null,undefined,''])assert.equal(renderToStaticMarkup(React.createElement(Media,{src})), '');});
test('failed image is removed without hiding job data or actions',()=>{assert.match(source,/failedSource === src/);assert.match(source,/onError=\{\(\) => setFailedSource\(src\)\}/);assert.match(app,/src=\{job.image_data\} \/>/);});
test('compact action sizing overrides legacy full height and media ratios',()=>{assert.match(css,/height:auto;min-height:48px;max-height:none;aspect-ratio:auto/);assert.match(css,/align-items:start;align-content:start/);assert.match(css,/\.file-action input \{width:1px;height:1px;min-height:0/);});
test('badges replace technical payment label and preserve meaningful status',()=>{assert.equal(adminBadgeText('not_required'),'No payment required');assert.equal(adminBadgeText('comp'),'Admin Promo / COMP');assert.equal(adminBadgeText('expired'),'expired');});
test('formatted dates preserve instant and local timezone, invalid values stay safe',()=>{assert.equal(adminDate(null),'—');assert.equal(adminDate('bad'),'—');assert.equal(adminDate('2026-09-26T12:00:00Z'),new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date('2026-09-26T12:00:00Z')));});
test('Job status and payment are not redundantly repeated',()=>{const jobs=app.slice(app.indexOf('<section className="admin-section admin-tab-jobs"'),app.indexOf('<section className="admin-section admin-tab-marketplace"'));assert.ok(jobs.includes('aw-badges'));assert.doesNotMatch(jobs,/Status: \{job.status|Payment: \{job.payment_status/);});
test('refresh feedback is compact and disabled through authorization plus load',()=>{const s=readFileSync('src/components/AdminWorkspace.jsx','utf8');assert.match(s,/disabled=\{refreshing\}/);assert.match(s,/aw-refresh-feedback/);assert.match(s,/Updated just now/);});
test('password eye remains non-submit and admin uses existing session authentication',()=>{assert.match(app,/PasswordField autoComplete="current-password"/);assert.match(app,/inputProps=\{\{value: adminPassword/);assert.match(app,/await controller.login\(\{ email: adminEmail.trim\(\), password: adminPassword \}\)/);});
