import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {sql,sqlAsync,file,auth} from './pg.mjs';
const owner='10000000-0000-0000-0000-000000000001',other='10000000-0000-0000-0000-000000000002',admin='10000000-0000-0000-0000-000000000003';
const b=randomUUID(),b2=randomUUID();
import {apple} from './common-lock-fixture.mjs';
sql(`insert into auth.users values('${other}')`);
sql(`begin;set local request.jwt.claim.role='service_role';insert into business_submissions(id,business_name,status,plan,advertiser_user_id,owner_user_id,placement_source,payment_status) values('${b}','Synthetic COMP','approved','Free','${owner}','${owner}','paid','not_required'),('${b2}','Other synthetic','approved','Free','${other}','${other}','paid','not_required');commit;`);
const grantSQL=(plan='premium',key=randomUUID(),id=b)=>`select grant_admin_comp('${id}','${plan}',30,'${key}')`;
const grant=(plan='premium',key=randomUUID(),id=b)=>{sql(auth(grantSQL(plan,key,id),admin));return key;};
const revoke=(key,id=b)=>sql(auth(`select revoke_admin_comp('${id}','${key}')`,admin));
const gate=(id=b,who=owner)=>sql(auth(`select coalesce(premium_event_provider('${id}'),'DENY')`,who));
const fields=JSON.stringify({title:'Synthetic COMP event',place:'Synthetic venue',event_date:'2099-01-01',event_time:'10:00 AM'});
const submit=(id=b,who=owner)=>sql(auth(`select submit_premium_event('${id}','${randomUUID()}','${fields}')`,who));
test('legacy labels not backfilled',()=>{assert.equal(sql('select count(*) from admin_comp_authority'),'0');assert.match(gate(),/DENY/);});
for(const plan of ['Free','Featured','Premium'])test(`${plan} label alone denied`,()=>{sql(`update business_submissions set plan='${plan}',placement_source='comp',placement_expires_at='2099-01-01' where id='${b}'`);assert.match(gate(),/DENY/);assert.throws(()=>submit());});
test('anon cannot grant',()=>assert.throws(()=>sql('set role anon;'+grantSQL())));
test('advertiser cannot grant',()=>assert.throws(()=>sql(auth(grantSQL(),owner)),/ADMIN_REQUIRED/));
test('advertiser cannot revoke',()=>assert.throws(()=>sql(auth(`select revoke_admin_comp('${b}',null)`,owner)),/ADMIN_REQUIRED/));
for(const role of ['anon','authenticated','service_role'])test(`${role} cannot forge authority/audit`,()=>{for(const table of ['admin_comp_authority','admin_comp_audit'])assert.throws(()=>sql(`set role ${role};delete from ${table}`),/permission denied/);});
test('Featured COMP projects Featured benefits but Events denied',()=>{grant('featured');assert.match(gate(),/DENY/);assert.throws(()=>submit());assert.equal(sql(`select plan||':'||placement_source from business_submissions where id='${b}'`),'Featured:comp');});
test('Premium COMP trusted actor dates and benefits',()=>{const key=grant();assert.match(gate(),/admin_comp/);assert.equal(sql(`select granted_by='${admin}' and starts_at=granted_at and expires_at>starts_at from admin_comp_authority where id='${key}'`),'t');assert.equal(sql(`select plan||':'||placement_source from business_submissions where id='${b}'`),'Premium:comp');});
test('wrong owner denied',()=>{assert.match(gate(b,other),/DENY/);assert.throws(()=>submit(b,other));});
test('wrong business denied',()=>{assert.match(gate(b2,other),/DENY/);assert.throws(()=>submit(b2,other));});
test('expired denied automatically',()=>{sql(`update admin_comp_authority set starts_at=now()-interval '2 days',expires_at=now()-interval '1 day' where business_id='${b}' and status='active'`);assert.match(gate(),/DENY/);assert.throws(()=>submit());});
test('future start denied',()=>{const key=grant();sql(`update admin_comp_authority set starts_at=now()+interval '1 day' where id='${key}'`);assert.match(gate(),/DENY/);});
test('revoked denied and audit retained',()=>{const key=grant();revoke(key);assert.match(gate(),/DENY/);assert.throws(()=>submit());assert.equal(sql(`select count(*) from admin_comp_audit where grant_id='${key}'`),'2');});
test('duplicate grant idempotent and cannot resurrect revoked grant',()=>{const key=grant();const end=sql(`select expires_at from admin_comp_authority where id='${key}'`);grant('premium',key);assert.equal(sql(`select expires_at from admin_comp_authority where id='${key}'`),end);revoke(key);grant('premium',key);assert.match(gate(),/DENY/);assert.throws(()=>grant('featured',key),/IDEMPOTENCY_CONFLICT/);});
test('stale revoke cannot remove replacement',()=>{const old=grant();const current=grant();revoke(old);assert.equal(sql(`select status from admin_comp_authority where id='${current}'`),'active');assert.match(gate(),/admin_comp/);});
test('legacy clear records present action without invented grant',()=>{sql(`update business_submissions set placement_source='comp' where id='${b2}'`);sql(auth(`select revoke_admin_comp('${b2}',null)`,admin));assert.equal(sql(`select count(*) from admin_comp_audit where business_id='${b2}' and action='legacy_clear' and grant_id is null`),'1');});
test('legacy clear cannot revoke real authority',()=>assert.throws(()=>sql(auth(`select revoke_admin_comp('${b}',null)`,admin)),/LEGACY_COMP_REQUIRED/));
test('0,1,2 slots allowed; 3 slots denied; pending only',()=>{grant();for(let n=0;n<3;n++){assert.match(sql(auth(`select can_submit from premium_event_options() where business_id='${b}'`,owner)),/\nt\n/);submit();}assert.throws(()=>submit());assert.equal(sql(`select count(*) from event_submissions where business_id='${b}' and status='pending' and entitlement_provider='admin_comp'`),'3');});
test('approved event remains after revoke, new submissions denied',()=>{const id=sql(`select id from event_submissions where business_id='${b}' limit 1`);sql(auth(`select moderate_premium_event('${id}','approved')`,admin));const key=sql(`select id from admin_comp_authority where business_id='${b}' and status='active'`);revoke(key);assert.equal(sql(`select status from event_submissions where id='${id}'`),'approved');assert.throws(()=>submit());});
test('grant/revoke concurrency serialized; no resurrection via stale target',async()=>{const old=grant();const key=randomUUID();await Promise.all([sqlAsync(auth(grantSQL('premium',key),admin)),sqlAsync(auth(`select revoke_admin_comp('${b}','${old}')`,admin))]);assert.equal(sql(`select count(*) from admin_comp_authority where business_id='${b}' and status='active'`),'1');assert.equal(sql(`select status from admin_comp_authority where id='${key}'`),'active');});
test('duplicate concurrent grants create one audit grant',async()=>{const key=randomUUID();await Promise.all(Array.from({length:10},()=>sqlAsync(auth(grantSQL('premium',key),admin))));assert.equal(sql(`select count(*) from admin_comp_audit where grant_id='${key}' and action='grant'`),'1');});
test('paid binding prevents COMP overwrite',()=>{sql(`update business_submissions set stripe_subscription_id='synthetic-bound' where id='${b2}'`);assert.throws(()=>grant('premium',randomUUID(),b2),/PAID_PROVIDER_BOUND/);});
test('new common gate preserves authoritative Stripe and terminal denial',()=>{
 sql(`insert into stripe_promotion_authority(subscription_id,listing_type,listing_id,environment,plan,status,period_end,cancel_at_period_end,event_created,event_id,snapshot) values('synthetic-bound','business','${b2}','Production','premium','active','2099-01-01',false,1,'evt_comp_regression','{}')`);
 assert.match(gate(b2,other),/stripe/);submit(b2,other);
 sql("update stripe_promotion_authority set status='canceled' where subscription_id='synthetic-bound'");assert.match(gate(b2,other),/DENY/);assert.throws(()=>submit(b2,other));
});
test('new common gate preserves Apple Production and provider isolation',()=>{
 sql(`update business_submissions set stripe_subscription_id=null,payment_status='not_required',placement_source='apple' where id='${b2}'`);
 sql(apple(b2,{entitlement:true}));
 assert.match(gate(b2,other),/apple/);submit(b2,other);assert.throws(()=>grant('premium',randomUUID(),b2),/PAID_PROVIDER_BOUND/);
 sql(`update listing_promotion_entitlements set status='revoked' where listing_id='${b2}'`);assert.match(gate(b2,other),/DENY/);
});
test('advertiser plan tampering cannot grant COMP',()=>{
 const before=sql(`select plan||':'||placement_source from business_submissions where id='${b2}'`);
 const result=sql(auth(`update business_submissions set plan='Premium',placement_source='comp' where id='${b2}'`,other));
 assert.match(result,/UPDATE 0/);assert.equal(sql(`select plan||':'||placement_source from business_submissions where id='${b2}'`),before);assert.match(gate(b2,other),/DENY/);
});
