import {useEffect,useState} from 'react';
export default function ApplePromotionPurchase({client,bridge,onChanged,onLegal}){
 const [session,setSession]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[listings,setListings]=useState([]),[selection,setSelection]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!client)return;let active=true;const apply=async s=>{if(!active)return;setSession(s);if(!s){setListings([]);return;}const r=await client.rpc('advertiser_my_listings');if(active){setListings((r.data??[]).filter(l=>['pending','approved'].includes(l.status)));if(r.error)setMessage('Your listings are temporarily unavailable.');}};client.auth.getSession().then(r=>apply(r.data.session));const {data}=client.auth.onAuthStateChange((_e,s)=>{setTimeout(()=>apply(s),0);});return()=>{active=false;data.subscription.unsubscribe();};},[client]);
 useEffect(()=>{const changed=bridge.addListener('promotionChanged',()=>onChanged?.()),legal=bridge.addListener('openLegal',e=>{if(['terms','privacy'].includes(e.page))onLegal?.(e.page);});return()=>{changed.then(h=>h.remove());legal.then(h=>h.remove());};},[bridge,onChanged,onLegal]);
 async function signIn(event){event.preventDefault();if(!client||busy)return;setBusy(true);try{const r=await client.auth.signInWithPassword({email,password});setPassword('');setMessage(r.error?'Sign-in failed. Check your email and password.':'Signed in.');}finally{setBusy(false);}}
 async function register(){if(!client||busy)return;setBusy(true);try{const r=await client.auth.signUp({email,password});setPassword('');setMessage(r.error?'Account could not be created. Please try again.':'Check your email to confirm your account, then sign in.');}finally{setBusy(false);}}
 async function open(){const listing=listings.find(l=>l.listing_type+':'+l.id===selection);if(!listing||busy)return;setBusy(true);try{const r=await client.auth.getSession();if(!r.data.session)throw Error();await bridge.open({accessToken:r.data.session.access_token,listingType:listing.listing_type,listingId:listing.id});}catch{setMessage('Apple subscriptions are temporarily unavailable.');}finally{setBusy(false);}}
 return <section aria-label="Apple promotions">{!session?<form onSubmit={signIn}><h2>Sign in to promote your listing</h2><label>Email<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy||!client}>Sign in</button><button type="button" disabled={busy||!email||password.length<8} onClick={register}>Create account</button></form>:<><label>Your listing<select value={selection} onChange={e=>setSelection(e.target.value)}><option value="">Choose a listing</option>{listings.map(l=><option key={l.listing_type+':'+l.id} value={l.listing_type+':'+l.id}>{l.title}</option>)}</select></label>{listings.length===0&&<p>Publish a listing while signed in to promote it. Existing listings must belong to your account.</p>}<button className="plan-card" disabled={!selection||busy} onClick={open}><span className="plan-name">Featured / Premium</span><span className="plan-note">See Apple prices and subscribe</span></button></>}<p role="status">{message}</p></section>;
}
