import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {setup} from './fixtures.mjs';
import {BUNDLE,uuid,iso} from '../../supabase/functions/_shared/apple/domain.mjs';
import {handler} from '../../supabase/functions/_shared/apple/http.mjs';
import {resolveEffectivePromotion} from '../../supabase/functions/_shared/apple/projection.mjs';
import {UnconfiguredAppleVerifier,OfficialAppleVerifierAdapter} from '../../supabase/functions/_shared/apple/apple-verifier.mjs';
import {PostgresAppleRepository} from '../../supabase/functions/_shared/apple/repository.mjs';
const reject=(promise,code)=>assert.rejects(promise,e=>e.code===code);
async function ready(){const f=await setup();f.token=await f.buyer();f.list=await f.listing(f.token);return f;}
async function delivered(){const f=await ready();f.p=await f.purchase(f.token,f.list);f.result=await f.backend.verify(f.token,f.p.input);return f;}
function notification(f,type,overrides={}) {
  return {bundle_id:BUNDLE,environment:'Sandbox',notification_uuid:uuid(),notification_type:type,subtype:null,signed_date:f.now()+1,
    original_transaction_id:f.p.t.original_transaction_id,transaction_id:f.p.t.transaction_id,product_id:f.p.t.product_id,
    app_account_token:f.p.t.app_account_token,app_transaction_id:f.p.t.app_transaction_id,period_start:f.p.t.purchase_date,period_end:f.p.t.expires_date,
    transaction:f.p.t,...overrides};
}
test('01 buyer idempotent under concurrent verified bootstrap',async()=>{const f=await setup();await Promise.all([f.buyer(),f.buyer()]);assert.equal(f.store.state.buyers.length,1);});
test('02 appAccountToken stable; capability plaintext never persisted',async()=>{const f=await ready(),token=f.store.state.buyers[0].app_account_token;await f.buyer();assert.equal(f.store.state.buyers[0].app_account_token,token);assert.ok(!JSON.stringify(f.store.state).includes(f.token));});
test('03 idempotency key binds listing and plan',async()=>{const f=await ready();await f.backend.prepare(f.token,f.list);await reject(f.backend.prepare(f.token,{...f.list,requested_plan:'premium'}),'IDEMPOTENCY_CONFLICT');});
test('04 double tap produces one intent and slot',async()=>{const f=await ready();const [a,b]=await Promise.all([f.backend.prepare(f.token,f.list),f.backend.prepare(f.token,f.list)]);assert.equal(a.purchase_intent_id,b.purchase_intent_id);assert.equal(f.store.state.slots.length,1);});
test('05 two buyers isolated even with same idempotency key',async()=>{const f=await ready(),b=await f.buyer('B'),l=await f.listing(b);l.idempotency_key=f.list.idempotency_key;await f.backend.prepare(f.token,f.list);await f.backend.prepare(b,l);assert.equal(f.store.state.intents.length,2);await reject(f.backend.prepare(b,{...f.list,idempotency_key:uuid()}),'LISTING_UNAUTHORIZED');});
test('06 slots one through ten across business/job/rental',async()=>{const f=await setup(),a=await f.buyer();for(let i=0;i<10;i++){const p=await f.backend.prepare(a,await f.listing(a,['business','job','rental'][i%3]));assert.equal(p.slot_number,i+1);}});
test('07 eleventh intent rejected without deleting history',async()=>{const f=await setup(),a=await f.buyer();for(let i=0;i<10;i++)await f.backend.prepare(a,await f.listing(a));await reject(f.backend.prepare(a,await f.listing(a)),'NO_SLOT_AVAILABLE');assert.equal(f.store.state.slots.length,10);});
test('08 missing listing rejected',async()=>{const f=await ready();await reject(f.backend.prepare(f.token,{...f.list,listing_id:uuid()}),'LISTING_NOT_FOUND');});
test('09 unauthorized listing rejected despite legacy ownership',async()=>{const f=await ready();f.store.state.grants=[];await reject(f.backend.prepare(f.token,f.list),'LISTING_UNAUTHORIZED');});
for(const [n,key] of [[10,'product_id'],[11,'buyer_id'],[12,'environment']])test(`${n} caller cannot choose ${key}`,async()=>{const f=await ready();await reject(f.backend.prepare(f.token,{...f.list,[key]:'forged'}),'INVALID_INPUT');});
test('13 replay cannot move transaction to another intent',async()=>{const f=await delivered();const other=await f.purchase(f.token,await f.listing(f.token));await reject(f.backend.verify(f.token,{...other.input,transaction_jws:f.p.input.transaction_jws}),'TRANSACTION_REPLAY_CONFLICT');});
test('14 duplicate notification processed once',async()=>{const f=await delivered(),h=f.verifier.register(notification(f,'DID_CHANGE_RENEWAL_STATUS',{auto_renew_enabled:false}));await f.backend.notification(h);await f.backend.notification(h);assert.equal(f.store.state.notifications.length,1);assert.equal(f.store.state.notifications[0].attempts,1);});
test('15 old renewal-status event cannot overwrite newer facts',async()=>{const f=await delivered();await f.backend.notification(f.verifier.register(notification(f,'DID_CHANGE_RENEWAL_STATUS',{auto_renew_enabled:false,signed_date:f.now()+2})));await f.backend.notification(f.verifier.register(notification(f,'DID_CHANGE_RENEWAL_STATUS',{auto_renew_enabled:true,signed_date:f.now()+1})));assert.equal(f.store.state.subscriptions[0].status,'active_nonrenewing');assert.equal(f.store.state.notifications[1].status,'quarantined');});
for(const [n,type,expected,extra] of [[16,'REFUND','revoked',{}],[17,'REVOKE','revoked',{}],[18,'DID_FAIL_TO_RENEW','grace',{grace:true}],[19,'DID_FAIL_TO_RENEW','billing_retry',{}],[20,'EXPIRED','expired',{}]])test(`${n} ${type} maps verified state without adding days`,async()=>{const f=await delivered(),end=f.store.state.subscriptions[0].period_end;const ev=notification(f,type,extra.grace?{grace_period_expires_at:iso(f.now()+3600000)}:{});await f.backend.notification(f.verifier.register(ev));assert.equal(f.store.state.subscriptions[0].status,expected);assert.equal(f.store.state.subscriptions[0].period_end,end);assert.equal(f.store.state.slots.length,1);});
test('21 known chain cannot be assigned another listing',async()=>{const f=await delivered();const p=await f.purchase(f.token,await f.listing(f.token),{original_transaction_id:f.p.t.original_transaction_id});const r=await f.backend.verify(f.token,p.input);assert.equal(r.status,'reconciliation');assert.equal(f.store.state.assignments.length,1);assert.equal(f.store.state.assignments[0].listing_id,f.list.listing_id);});
test('22 same transaction replay one delivery and entitlement',async()=>{const f=await delivered();const r=await f.backend.verify(f.token,f.p.input);assert.equal(r.status,'already_delivered');assert.equal(r.delivery_id,f.result.delivery_id);assert.equal(f.store.state.deliveries.length,1);assert.equal(f.store.state.entitlements.length,1);});
test('23 Sandbox ledger never grants Production projection',async()=>{const f=await delivered(),l=f.store.state.listings[0];assert.equal(resolveEffectivePromotion(l,f.store.state.entitlements,'Production',f.now()).plan,'free');assert.equal(resolveEffectivePromotion(l,f.store.state.entitlements,'Sandbox',f.now()).plan,'featured');});
test('24 Xcode and Production evidence fail closed',async()=>{for(const environment of ['Xcode','Production']){const f=await ready(),p=await f.purchase(f.token,f.list,{environment});await reject(f.backend.verify(f.token,p.input),'ENVIRONMENT_DISABLED');assert.equal(f.store.state.deliveries.length,0);}});
test('25 Stripe conflict does not start Apple flow',async()=>{const f=await ready();f.store.state.listings[0].stripe_conflict=true;await reject(f.backend.prepare(f.token,f.list),'STRIPE_CONFLICT');assert.equal(f.store.state.slots.length,0);});
test('26 inferior comp does not downgrade paid Premium',async()=>{const f=await delivered(),l=f.store.state.listings[0],paid={...f.store.state.entitlements[0],plan:'premium'};const comp={...paid,provider:'comp',plan:'featured',source_priority:999};assert.equal(resolveEffectivePromotion(l,[paid,comp],'Sandbox',f.now()).plan,'premium');});
test('27 Premium beats Featured without summing validity; paid conflict visible',async()=>{const f=await delivered(),l=f.store.state.listings[0],a=f.store.state.entitlements[0],b={...a,provider:'stripe',plan:'premium',valid_until:iso(f.now()+10000)};const r=resolveEffectivePromotion(l,[a,b],'Sandbox',f.now());assert.equal(r.plan,'premium');assert.equal(r.valid_until,b.valid_until);assert.deepEqual(r.conflicts,['MULTIPLE_PAID_ENTITLEMENTS']);});
test('28 hidden/deleted listing never reactivated by notification',async()=>{const f=await delivered();f.store.state.listings[0].status='hidden';await f.backend.notification(f.verifier.register(notification(f,'SUBSCRIBED')));assert.equal(resolveEffectivePromotion(f.store.state.listings[0],f.store.state.entitlements,'Sandbox',f.now()).visible,false);f.store.state.listings=[];assert.equal(f.store.state.listings.length,0);assert.equal(f.store.state.assignments.length,1);});
test('29 delivery confirmation tampering rejected',async()=>{const f=await delivered(),c=f.result.confirmation,parts=c.signed_jws.split('.');const payload=JSON.parse(Buffer.from(parts[1],'base64url'));payload.listing_id=uuid();parts[1]=Buffer.from(JSON.stringify(payload)).toString('base64url');assert.equal(await f.signer.verify({...c,signed_jws:parts.join('.')},{},f.now()/1000),false);});
test('30 expired delivery confirmation rejected',async()=>{const f=await delivered();assert.equal(await f.signer.verify(f.result.confirmation,{},f.now()/1000+301),false);});
test('31 wrong transaction confirmation rejected',async()=>{const f=await delivered();assert.equal(await f.signer.verify(f.result.confirmation,{transactionId:'wrong'},f.now()/1000),false);});
test('32 wrong listing confirmation rejected; correct binding accepted',async()=>{const f=await delivered();assert.equal(await f.signer.verify(f.result.confirmation,{listing_id:uuid()},f.now()/1000),false);assert.equal(await f.signer.verify(f.result.confirmation,{listing_id:f.list.listing_id,transactionId:f.p.t.transaction_id},f.now()/1000),true);});
test('33 ten concurrent reservations cannot double allocate slots',async()=>{const f=await setup(),a=await f.buyer(),inputs=[];for(let i=0;i<10;i++)inputs.push(await f.listing(a));const r=await Promise.all(inputs.map(l=>f.backend.prepare(a,l)));assert.equal(new Set(r.map(x=>x.slot_number)).size,10);});
test('34 notification before client verify waits for assignment',async()=>{const f=await ready();f.p=await f.purchase(f.token,f.list);const h=f.verifier.register(notification(f,'SUBSCRIBED'));assert.equal((await f.backend.notification(h)).status,'retry');assert.equal(f.store.state.deliveries.length,0);await f.backend.verify(f.token,f.p.input);await f.backend.reconciliation(f.token);assert.equal(f.store.state.notifications[0].status,'processed');assert.equal(f.store.state.deliveries.length,1);});
test('35 crash before and lost response after commit are retry idempotent',async()=>{const f=await ready(),p=await f.purchase(f.token,f.list);f.store.crashBefore=true;await assert.rejects(f.backend.verify(f.token,p.input));assert.equal(f.store.state.deliveries.length,0);f.store.crashAfter=true;await assert.rejects(f.backend.verify(f.token,p.input));assert.equal(f.store.state.deliveries.length,1);const r=await f.backend.verify(f.token,p.input);assert.equal(r.status,'already_delivered');assert.equal(f.store.state.entitlements.length,1);});
test('36 signer failure occurs after durable delivery and retries do not duplicate',async()=>{const f=await ready(),p=await f.purchase(f.token,f.list);f.backend.signer={async sign(){throw new Error('TEST_SIGNER_DOWN');}};await assert.rejects(f.backend.verify(f.token,p.input));assert.equal(f.store.state.deliveries.length,1);f.backend.signer=f.signer;assert.equal((await f.backend.verify(f.token,p.input)).status,'already_delivered');});
test('37 expired purchasing reserve is reconciliation, never free',async()=>{const f=await ready();await f.purchase(f.token,f.list);f.advance(600001);await f.backend.reconciliation(f.token);assert.equal(f.store.state.slots[0].state,'reconciliation');assert.equal(f.store.state.slots.length,1);});
test('38 HTTP deployed composition rejects every operation without dependencies',async()=>{for(const kind of ['prepare','verify','notifications']){const r=await handler(kind)(new Request('https://example.invalid',{method:'POST',body:JSON.stringify({verified:true})}));assert.equal(r.status,503);}});
test('39 fixture handles/verified booleans are not accepted by default verifier',async()=>{const v=new UnconfiguredAppleVerifier();await reject(v.verifyTransaction('TEST-EVIDENCE'), 'APPLE_VERIFIER_NOT_CONFIGURED');await reject(v.verifyNotification({verified:true}), 'APPLE_VERIFIER_NOT_CONFIGURED');});
test('40 expired/revoked capability and installation rejected',async()=>{for(const mutate of [s=>s.capabilities[0].revoked_at=iso(1),s=>s.capabilities[0].expires_at=iso(1),s=>s.installations[0].revoked_at=iso(1)]){const f=await ready();mutate(f.store.state);await assert.rejects(f.backend.prepare(f.token,f.list));assert.equal(f.store.state.intents.length,0);}});
test('41 DID_RENEW records exact signed period and transaction once',async()=>{const f=await delivered(),transaction={...f.p.t,transaction_id:'999',purchase_date:iso(f.now()+1),expires_date:iso(f.now()+172800000)};const h=f.verifier.register(notification(f,'DID_RENEW',{transaction_id:'999',period_start:transaction.purchase_date,period_end:transaction.expires_date,transaction}));await f.backend.notification(h);await f.backend.notification(h);assert.equal(f.store.state.transactions.length,2);assert.equal(f.store.state.deliveries.length,2);assert.equal(f.store.state.entitlements.length,1);assert.equal(f.store.state.entitlements[0].valid_until,transaction.expires_date);});
test('42 GRACE_PERIOD_EXPIRED removes active grace without freeing slot',async()=>{const f=await delivered();await f.backend.notification(f.verifier.register(notification(f,'GRACE_PERIOD_EXPIRED')));assert.equal(f.store.state.subscriptions[0].status,'billing_retry');assert.equal(f.store.state.slots[0].state,'occupied');});
test('43 forged verified transaction fields rejected by domain',async()=>{for(const fields of [{app_account_token:uuid()},{product_id:'fake'},{subscription_group_id:'wrong'},{ownership_type:'FAMILY_SHARED'},{is_upgraded:true},{revocation_date:iso(1)},{expires_date:iso(1)}]){const f=await ready(),p=await f.purchase(f.token,f.list,fields);await assert.rejects(f.backend.verify(f.token,p.input));assert.equal(f.store.state.deliveries.length,0);}});
test('44 migrations RLS and RPC grants are explicitly closed (static, not SQL execution)',()=>{const s=readFileSync(new URL('../../supabase/migrations/202609080001_apple_iap_ledger.sql',import.meta.url),'utf8');assert.match(s,/NOT APPLIED/);assert.match(s,/enable row level security/);assert.match(s,/revoke all on public\.%I from public,anon,authenticated/);assert.match(s,/for update/);assert.match(s,/v<>expected_version/);assert.match(s,/ENVIRONMENT_DISABLED/);assert.doesNotMatch(s,/update public\.(business_submissions|job_listings|rental_listings)/);assert.doesNotMatch(s,/references auth\.users|advertiser_profiles/);});
test('45 Postgres port uses one atomic RPC and fails closed on database error',async()=>{const calls=[],r=new PostgresAppleRepository(async(name,args)=>{calls.push([name,args]);return {data:true};});assert.equal(await r.compareAndSwap(4,{}),true);assert.equal(calls[0][0],'apple_ledger_compare_and_swap');const bad=new PostgresAppleRepository(async()=>({error:true}));await reject(bad.read(),'LEDGER_UNAVAILABLE');});
test('46 production confirmation is never fabricated by fixture signer',async()=>{const f=await delivered();assert.equal(f.result.confirmation.kind,'TEST-ONLY.apple.delivery.v1');assert.notEqual(f.result.confirmation.kind,'abilene.apple.delivery.v1');});
test('47 official adapter delegates both proofs, never trusts a decoded client boolean',async()=>{
 const calls=[];const raw={bundleId:BUNDLE,environment:'Sandbox',transactionId:'1',originalTransactionId:'1',productId:'test',appAccountToken:uuid(),appTransactionId:'app',subscriptionGroupIdentifier:'g',purchaseDate:1800000000000,expiresDate:1800000010000,inAppOwnershipType:'PURCHASED'};
 const adapter=new OfficialAppleVerifierAdapter({async verifyAndDecodeTransaction(jws){calls.push(jws);return raw;},async verifyAndDecodeAppTransaction(jws){calls.push(jws);return {bundleId:BUNDLE,receiptType:'Sandbox',appTransactionId:'app'};}});
 const t=await adapter.verifyTransaction('opaque-t','opaque-a');assert.deepEqual(calls,['opaque-t','opaque-a']);assert.equal(t.transaction_id,'1');assert.equal(t.purchase_date,iso(raw.purchaseDate));
});
test('48 official adapter rejects mismatched AppTransaction identity',async()=>{
 const adapter=new OfficialAppleVerifierAdapter({async verifyAndDecodeTransaction(){return {bundleId:BUNDLE,environment:'Sandbox',appTransactionId:'A'};},async verifyAndDecodeAppTransaction(){return {bundleId:BUNDLE,receiptType:'Sandbox',appTransactionId:'B'};}});
 await reject(adapter.verifyTransaction('t','a'),'APP_TRANSACTION_MISMATCH');
});
test('49 expired listing grant and disabled catalog reject preparation',async()=>{
 const f=await ready();f.store.state.grants[0].expires_at=iso(0);await reject(f.backend.prepare(f.token,f.list),'LISTING_UNAUTHORIZED');f.store.state.grants[0].expires_at=iso(f.now()+100000);f.store.state.catalog.forEach(p=>p.enabled=false);await reject(f.backend.prepare(f.token,f.list),'CATALOG_NOT_CONFIGURED');
});
test('50 late refund remains unresolved rather than silently accepted as stale',async()=>{
 const f=await delivered();await f.backend.notification(f.verifier.register(notification(f,'DID_CHANGE_RENEWAL_STATUS',{auto_renew_enabled:true,signed_date:f.now()+2})));
 await f.backend.notification(f.verifier.register(notification(f,'REFUND',{signed_date:f.now()+1})));
 assert.equal(f.store.state.subscriptions[0].status,'reconciliation');assert.equal(f.store.state.entitlements[0].status,'reconciliation');
});
test('51 HTTP rejects caller-supplied verified flag and never echoes opaque input',async()=>{
 const f=await ready(),h=handler('verify',f.backend);
 const r=await h(new Request('https://example.invalid',{method:'POST',headers:{authorization:'Bearer '+f.token},body:JSON.stringify({verified:true,transaction_jws:'DO-NOT-ECHO'})}));
 assert.equal(r.status,400);assert.ok(!(await r.text()).includes('DO-NOT-ECHO'));assert.equal(f.store.state.deliveries.length,0);
});
