import test from 'node:test';import assert from 'node:assert/strict';
import {compositionInput as f,contexts,responses,NOW} from './current-authentic-replay-fixture.mjs';
import {PortableCertificate} from '../../supabase/functions/_shared/apple/edge/certificates.mjs';
import {verifyOcsp,derTree} from '../../supabase/functions/_shared/apple/edge/ocsp.mjs';
import {verifyOcsp as nodeVerify} from '../../../abilene-apple-verifier/src/ocsp-verifier.mjs';
for(let i=0;i<2;i++)test('portable certificate verifies authentic Apple chain link '+i,async()=>{const c=new PortableCertificate(contexts[i].certificateDer),issuer=new PortableCertificate(contexts[i].issuerDer);assert.equal(await c.verify(issuer),true);assert.equal(await issuer.verify(c),false);});
for(let i=0;i<2;i++)test('portable OCSP identical verified facts to Node '+i,async()=>{const input={...contexts[i],responseDer:responses[i],evaluationTime:NOW};assert.deepEqual(await verifyOcsp(input),nodeVerify(input));});
for(let i=0;i<2;i++)test('portable OCSP altered signature rejects '+i,async()=>{const responseDer=Buffer.from(responses[i]);const oct=derTree(responseDer).children[1].children[0].children[1];const sig=derTree(responseDer.subarray(oct.value,oct.end)).children[2];responseDer[oct.value+sig.value+2]^=1;await assert.rejects(verifyOcsp({...contexts[i],responseDer,evaluationTime:NOW}));});
test('portable OCSP wrong issuer rejects',async()=>{await assert.rejects(verifyOcsp({...contexts[0],issuerDer:f.rootDer,responseDer:responses[0],evaluationTime:NOW}));});
test('portable OCSP stale response rejects',async()=>{await assert.rejects(verifyOcsp({...contexts[0],responseDer:responses[0],evaluationTime:NOW+365*86400000}));});
import {verifyAppleJws} from '../../supabase/functions/_shared/apple/edge/jws.mjs';
for(const name of ['transactionJws','appTransactionJws'])test('portable full Apple JWS '+name,async()=>{const r=await verifyAppleJws(f[name],{rootDer:f.rootDer,now:NOW});assert.equal(r.chain.length,3);assert.equal(r.payload.bundleId,'com.abilenevibes.app');});
test('portable JWS payload tamper rejected',async()=>{const p=f.transactionJws.split('.');p[1]=Buffer.from('{}').toString('base64url');await assert.rejects(verifyAppleJws(p.join('.'),{rootDer:f.rootDer,now:NOW}));});
test('untrusted root rejected',async()=>{await assert.rejects(verifyAppleJws(f.transactionJws,{rootDer:f.leafDer,now:NOW}));});
import {parseHttpResponse} from '../../supabase/functions/_shared/apple/edge/deno-transport.mjs';
test('OCSP HTTP fixed body and chunked framing',()=>{assert.equal(parseHttpResponse(Buffer.from('HTTP/1.1 200 OK\r\nContent-Length: 3\r\n\r\nabc')).stream[0].toString(),'abc');assert.equal(parseHttpResponse(Buffer.from('HTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\n\r\n3\r\nabc\r\n0\r\n\r\n')).stream[0].toString(),'abc');});
for(const input of ['HTTP/1.1 200 OK\r\nContent-Length: 4\r\n\r\nabc','HTTP/1.1 200 OK\r\nContent-Length: 3\r\nContent-Length: 3\r\n\r\nabc','HTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\nContent-Length: 3\r\n\r\nabc'])test('OCSP HTTP ambiguous/truncated framing rejects '+input.length,()=>assert.throws(()=>parseHttpResponse(Buffer.from(input))));
import {EdgeAppleVerifier} from '../../supabase/functions/_shared/apple/edge/verifier.mjs';
const verifier=()=>new EdgeAppleVerifier({rootDer:f.rootDer,environment:'Sandbox',catalog:[{product:'com.abilenevibes.app.promotion.slot01.featured.monthly',group:'22382531'}],clock:()=>NOW,transportFactory:resolve=>async h=>{const p=resolve(h);return p.certificateDer.equals(f.leafDer)?responses[0]:responses[1];}});
const context={intentId:'TEST',bundle:'com.abilenevibes.app',environment:'Sandbox',product:'com.abilenevibes.app.promotion.slot01.featured.monthly',group:'22382531'};
test('Edge verifier authentic JWS AppTransaction OCSP and unforgeable deadline',async()=>{const v=verifier(),t=await v.verifyTransaction(f.transactionJws,f.appTransactionJws,context);assert.equal(t.product_id,context.product);assert(v.verificationDeadline(t)>NOW);v.assertFresh(t,NOW,context);assert.throws(()=>v.verificationDeadline({...t}));});
for(const [key,value] of [['environment','Production'],['product','com.abilenevibes.app.promotion.slot01.premium.monthly'],['group','999']])test('Edge verifier context mismatch '+key,async()=>{await assert.rejects(verifier().verifyTransaction(f.transactionJws,f.appTransactionJws,{...context,[key]:value}));});
import {createTransport,isPublicAddress,validateUrl} from '../../supabase/functions/_shared/apple/edge/transport.mjs';
import {VerifiedCache} from '../../supabase/functions/_shared/apple/edge/cache.mjs';
const pairResolver=()=>contexts[0];
test('Edge production policy cannot start without public Apple app ID',()=>assert.throws(()=>new EdgeAppleVerifier({rootDer:f.rootDer,environment:'Production',catalog:[{product:context.product,group:context.group}],transportFactory:()=>()=>{}}),/APP_APPLE_ID_REQUIRED/));
test('Edge rejects unlisted products and missing groups at configuration',()=>{for(const catalog of [[{product:'unknown',group:'22382531'}],[{product:context.product,group:''}]])assert.throws(()=>new EdgeAppleVerifier({rootDer:f.rootDer,environment:'Sandbox',catalog,transportFactory:()=>()=>{}}),/CATALOG_CONFIG/);});
test('Edge transport rejects private and mixed DNS answers before exchange',async()=>{for(const address of ['127.0.0.1','10.0.0.1','169.254.169.254','::1','::ffff:127.0.0.1','192.168.1.1']){let called=false;const t=createTransport({enabled:true,pairResolver,resolve:async()=>[{address:'17.1.2.3'},{address}],exchange:async()=>{called=true;}});await assert.rejects(t({}),/SSRF_REJECTED/);assert.equal(called,false);assert.equal(isPublicAddress(address),false);}});
test('Edge transport URL rejects redirects in authority, credentials and query',()=>{for(const u of ['http://ocsp.apple.com.evil.test/ocsp03-a','http://u:p@ocsp.apple.com/ocsp03-a','http://ocsp.apple.com/ocsp03-a?x=1','file:///ocsp03-a'])assert.throws(()=>validateUrl(u));});
test('Edge transport pins validated IP and accepts only OCSP response',async()=>{let called=0;const t=createTransport({enabled:true,pairResolver,resolve:async()=>[{address:'17.1.2.3'}],exchange:async r=>{called++;assert.equal(r.address,'17.1.2.3');assert.equal(r.url.hostname,'ocsp.apple.com');return {status:200,headers:{'content-type':'application/ocsp-response'},stream:[responses[0]]};}});assert.deepEqual(await t({}),responses[0]);assert.equal(called,1);});
for(const status of [301,302,307,500])test('Edge transport rejects status '+status,async()=>{let calls=0;const t=createTransport({enabled:true,pairResolver,resolve:async()=>[{address:'17.1.2.3'}],exchange:async()=>{calls++;return {status,headers:{},stream:[]};}});await assert.rejects(t({}));assert.equal(calls,1);});
test('Edge transport aborts bounded timeout without retry',async()=>{let calls=0,signal;const t=createTransport({enabled:true,pairResolver,timeoutMs:10,resolve:async()=>[{address:'17.1.2.3'}],exchange:async r=>{calls++;signal=r.signal;return new Promise(()=>{});}});await assert.rejects(t({}),/TIMEOUT/);assert.equal(calls,1);assert.equal(signal.aborted,true);});
test('Edge cache x10 concurrent requests verify and fetch once',async()=>{const c=new VerifiedCache(()=>NOW);let calls=0;const values=await Promise.all(Array.from({length:10},()=>c.getOrRefresh(contexts[0],async()=>{calls++;return responses[0];})));assert.equal(calls,1);assert.equal(c.size,1);assert.equal(c.pendingCount,0);assert(values.every(v=>v===values[0]));});
test('Edge cache cannot accept fabricated verification facts',async()=>{const c=new VerifiedCache(()=>NOW);await assert.rejects(c.getOrRefresh(contexts[0],async()=>({status:'GOOD',signatureVerified:true})));assert.equal(c.size,0);});
test('Edge cache evicts expired verification',async()=>{let now=NOW;const c=new VerifiedCache(()=>now),r=await c.getOrRefresh(contexts[0],async()=>responses[0]);now=r.freshUntil;assert.equal(c.read(contexts[0]),null);assert.equal(c.size,0);});
test('Edge cache rejects rollback and clears prior entries',async()=>{let now=NOW;const c=new VerifiedCache(()=>now);await c.getOrRefresh(contexts[0],async()=>responses[0]);now--;assert.throws(()=>c.read(contexts[0]),/CLOCK_ROLLBACK/);assert.equal(c.size,0);});
test('Edge rejects altered type and ownership instead of coercing',()=>{const v=verifier(),t=JSON.parse(Buffer.from(f.transactionJws.split('.')[1],'base64url'));for(const change of [{isUpgraded:'false'},{inAppOwnershipType:'unknown'},{quantity:2}])assert.throws(()=>v.transaction({...t,...change}));});
test('Edge transaction brand expires and cannot move to another intent',async()=>{const v=verifier(),t=await v.verifyTransaction(f.transactionJws,f.appTransactionJws,context);assert.throws(()=>v.assertFresh(t,v.verificationDeadline(t),context));assert.throws(()=>v.assertFresh(t,NOW,{...context,intentId:'OTHER'}));});
import {APPLE_POLICY,APPLE_PRODUCTS,serverPolicy} from '../../supabase/functions/_shared/apple/production/policy.mjs';
test('confirmed production policy uses app6811679667 and same group for both real products',()=>{assert.equal(APPLE_POLICY.appAppleId,6811679667);assert.equal(serverPolicy().environment,'Production');assert.equal(APPLE_PRODUCTS.length,2);assert(APPLE_PRODUCTS.every(p=>p.group==='22382531'));assert.deepEqual(APPLE_PRODUCTS.map(p=>p.level),[2,1]);assert.throws(()=>serverPolicy('Xcode'));});
// Existing synthetic test PKI stays outside the shipping dependency graph.
import {fixture as diagnostic} from '../../../abilene-apple-verifier/tests/diagnostic-fixtures.mjs';
for(const [name,options,error] of [['revoked',{status:'revoked'},'REJECT_REVOKED'],['unknown',{status:'unknown'},'REJECT_UNKNOWN'],['missing nextUpdate',{next:false},'REJECT_MISSING_NEXT_UPDATE'],['multiple responses',{count:2},'REJECT_SINGLE_RESPONSE_COUNT'],['unauthorized responder',{unauthorized:true},'REJECT_RESPONDER_AUTHORIZATION']])test('replacement OCSP signed diagnostic rejects '+name,async()=>{const f=diagnostic(100,options),c=new VerifiedCache(()=>NOW);await assert.rejects(c.getOrRefresh(f.context,async()=>f.response),e=>e.code===error);assert.equal(c.size,0);});
test('replacement OCSP diagnostic valid pair verifies',async()=>{const d=diagnostic(101);assert.equal((await verifyOcsp({...d.context,responseDer:d.response,evaluationTime:NOW})).status,'GOOD');});
test('replacement OCSP rejects trailing DER',async()=>assert.rejects(verifyOcsp({...contexts[0],responseDer:Buffer.concat([responses[0],Buffer.from([0])]),evaluationTime:NOW}),e=>e.code==='REJECT_PARSE'));
test('replacement OCSP rejects future and just-stale signed responses',async()=>{const r=await verifyOcsp({...contexts[0],responseDer:responses[0],evaluationTime:NOW});for(const evaluationTime of [r.thisUpdate-61000,r.nextUpdate+61000])await assert.rejects(verifyOcsp({...contexts[0],responseDer:responses[0],evaluationTime}));});
test('replacement OCSP x32 pending bound and x33 eviction',async()=>{
 const ds=Array.from({length:33},(_,i)=>diagnostic(200+i)),c=new VerifiedCache(()=>NOW);
 let releaseFirst,releaseRest;
 const first=new Promise(r=>releaseFirst=r),rest=new Promise(r=>releaseRest=r);
 const jobs=ds.slice(0,32).map((d,i)=>c.getOrRefresh(d.context,()=> (i===0?first:rest).then(()=>d.response)));
 await Promise.resolve();assert.equal(c.pendingCount,32);
 await assert.rejects(c.getOrRefresh(ds[32].context,()=>ds[32].response),e=>e.code==='PENDING_CAPACITY');
 // FIFO is verification-completion order, not parallel request-start order.
 // Force entry 0 to finish first without changing crypto or cache behavior.
 releaseFirst();await jobs[0];assert.equal(c.size,1);
 releaseRest();await Promise.all(jobs);
 await c.getOrRefresh(ds[32].context,()=>ds[32].response);
 assert.equal(c.size,32);assert.equal(c.read(ds[0].context),null);
});
test('replacement JWS root policy never accepts synthetic PKI',async()=>{const d=diagnostic(301);await assert.rejects(verifyAppleJws(f.transactionJws,{rootDer:d.context.issuerDer,now:NOW}));});
test('authentic AppTransaction bootstrap is crypto/OCSP verified',async()=>{const v=verifier(),r=await v.verifyAppTransaction(f.appTransactionJws);assert.equal(r.environment,'Sandbox');assert(r.notAfter>NOW);});
// Payload-policy tests inject already-verified mock envelopes. Crypto tests above
// independently prove that production signed() cannot create these from unsigned input.
function productionPolicyFixture(){const v=new EdgeAppleVerifier({rootDer:f.rootDer,environment:'Production',appAppleId:6811679667,catalog:APPLE_PRODUCTS,clock:()=>NOW,transportFactory:()=>()=>{throw Error('NO_NETWORK');}});const payloads=new Map();v.signed=async key=>{assert(payloads.has(key));return {payload:payloads.get(key),until:NOW+15000,chain:[Buffer.from('MOCK')]};};return {v,payloads};}
for(const [name,change] of [['valid',{}],['wrong app',{appAppleId:1}],['wrong environment',{receiptType:'Sandbox'}],['wrong bundle',{bundleId:'other'}],['missing id',{appTransactionId:undefined}],['future',{receiptCreationDate:NOW+31000}]])test('production AppTransaction policy '+name,async()=>{const {v,payloads}=productionPolicyFixture();payloads.set('app',{bundleId:'com.abilenevibes.app',receiptType:'Production',appAppleId:6811679667,appTransactionId:'1120001',receiptCreationDate:NOW,...change});if(name==='valid')assert.equal((await v.verifyAppTransaction('app')).environment,'Production');else await assert.rejects(v.verifyAppTransaction('app'));});
for(const [name,change] of [['valid',{}],['wrong product',{productId:'wrong'}],['wrong lineage',{originalTransactionId:'999'}],['wrong token',{appAccountToken:crypto.randomUUID()}],['wrong env',{environment:'Sandbox'}],['missing status',{autoRenewStatus:undefined}]])test('notification renewal linkage '+name,async()=>{const {v,payloads}=productionPolicyFixture();const t={...JSON.parse(Buffer.from(f.transactionJws.split('.')[1],'base64url')),environment:'Production'};payloads.set('tx',t);payloads.set('renewal',{environment:'Production',originalTransactionId:t.originalTransactionId,productId:t.productId,autoRenewStatus:1,appAccountToken:t.appAccountToken,...change});payloads.set('notice',{version:'2.0',notificationUUID:crypto.randomUUID(),signedDate:NOW,notificationType:'DID_CHANGE_RENEWAL_STATUS',data:{bundleId:'com.abilenevibes.app',environment:'Production',appAppleId:6811679667,signedTransactionInfo:'tx',signedRenewalInfo:'renewal'}});if(name==='valid')v.assertNotificationFresh(await v.verifyNotification('notice'));else await assert.rejects(v.verifyNotification('notice'));});
test('verified TEST notification has no transaction or delivery authority',async()=>{const {v,payloads}=productionPolicyFixture();payloads.set('notice',{version:'2.0',notificationUUID:crypto.randomUUID(),signedDate:NOW,notificationType:'TEST',data:{bundleId:'com.abilenevibes.app',environment:'Production',appAppleId:6811679667}});const e=await v.verifyNotification('notice');v.assertNotificationFresh(e);assert.equal(e.transaction,undefined);assert.throws(()=>v.verificationDeadline(e));});
