import test from 'node:test';import assert from 'node:assert/strict';
import {bindingFixture} from './installation-binding-fixtures.mjs';
import {uuid,iso,sha256} from '../../supabase/functions/_shared/apple/domain.mjs';
const counts=f=>['deliveries','assignments','entitlements','transactions'].map(k=>f.store.state[k].length);
const empty=f=>assert.deepEqual(counts(f),[0,0,0,0]);
const once=f=>assert.deepEqual(counts(f),[1,1,1,1]);
const claims=r=>JSON.parse(Buffer.from(r.confirmation.signed_jws.split('.')[1],'base64url'));
test('origin context persists and normal origin succeeds',async()=>{const f=await bindingFixture(),i=f.store.state.intents[0];assert.equal(i.originating_installation_id,f.store.state.installations[0].installation_id);assert.equal(i.app_account_token,f.purchase.t.app_account_token);assert.equal(i.subscription_group_id,'22382531');const r=await f.verify();once(f);assert.equal(claims(r).installation_id,i.originating_installation_id);});
test('same buyer wrong installation normal verify rejects before Node or writes',async()=>{const f=await bindingFixture(),b=await f.installation();await assert.rejects(f.backend.verify(b,f.purchase.input),e=>e.code==='INSTALLATION_MISMATCH');empty(f);assert.equal(f.hooks.calls,0);assert.equal(f.signer.calls,0);});
test('wrong installation cannot prepare-replay or mark existing intent purchasing',async()=>{const f=await bindingFixture(),b=await f.installation();await assert.rejects(f.backend.prepare(b,f.listing),/INSTALLATION_MISMATCH/);await assert.rejects(f.backend.markPurchasing(b,f.purchase.input.purchase_intent_id),/INSTALLATION_MISMATCH/);empty(f);});
test('different buyer cannot reuse installation key',async()=>{const f=await bindingFixture();await f.buyer('other');await assert.rejects(f.installation(f.store.state.installations[0].key_id,f.store.state.buyers[1]),/INSTALLATION_CONFLICT/);empty(f);});
test('wrong buyer cannot use intent',async()=>{const f=await bindingFixture(),other=await f.buyer('other');await assert.rejects(f.backend.verify(other,f.purchase.input));empty(f);});
test('legacy null installation fails closed',async()=>{const f=await bindingFixture();f.store.state.intents[0].originating_installation_id=null;await assert.rejects(f.verify(),/INTENT_BINDING_REQUIRED/);empty(f);});
test('unconsumed intent cannot be adopted even with signed recovery grant',async()=>{const f=await bindingFixture(),b=await f.installation(),g=await f.grant(b);await assert.rejects(f.recover(b,g),/RECOVERY_REQUIRES_DELIVERY/);empty(f);});
test('lost ACK same originating installation recovers exact durable state',async()=>{const f=await bindingFixture();f.store.crashAfter=true;await assert.rejects(f.verify());once(f);f.store.crashAfter=false;const r=await f.verify();assert.equal(r.status,'already_delivered');once(f);assert.equal(claims(r).installation_id,f.store.state.intents[0].originating_installation_id);});
for(const kind of ['new installation','reinstall','new device'])test('explicit delivered recovery '+kind,async()=>{const f=await bindingFixture(),first=await f.verify(),b=await f.installation(kind),g=await f.grant(b),r=await f.recover(b,g);assert.equal(r.delivery_id,first.delivery_id);assert.notEqual(claims(r).installation_id,f.store.state.intents[0].originating_installation_id);assert.equal(claims(r).appAccountToken,f.purchase.t.app_account_token);once(f);assert.equal(f.store.state.challenges.filter(c=>c.purpose==='delivery-recovery-v1').length,1);});
test('delivered normal verify on another installation still rejects',async()=>{const f=await bindingFixture();await f.verify();const b=await f.installation();await assert.rejects(f.backend.verify(b,f.purchase.input),/INSTALLATION_MISMATCH/);once(f);});
test('recovery requires configured server authority',async()=>{const f=await bindingFixture();await f.verify();const b=await f.installation();f.backend.recoveryAuthorizer=undefined;await assert.rejects(f.recover(b,'client-verified'),/RECOVERY_NOT_CONFIGURED/);once(f);});
for(const [name,field,value] of [['buyer','buyer_id',()=>uuid()],['installation','installation_id',()=>uuid()],['listing','listing_id',()=>uuid()],['token','app_account_token',()=>uuid()],['product','product_id',()=> 'wrong'],['group','subscription_group_id',()=> 'wrong'],['bundle','bundle_id',()=> 'wrong'],['environment','environment',()=> 'Production'],['lineage','original_transaction_id',()=> 'wrong'],['intent','purchase_intent_id',()=>uuid()],['delivery','delivery_id',()=>uuid()]])test('signed recovery grant rejects wrong '+name,async()=>{const f=await bindingFixture();await f.verify();const b=await f.installation(),g=await f.grant(b,{[field]:value()});await assert.rejects(f.recover(b,g),/RECOVERY_AUTHORIZATION_REJECTED/);once(f);assert.equal(f.store.state.challenges.length,0);});
test('expired recovery grant rejected',async()=>{const f=await bindingFixture();await f.verify();const b=await f.installation(),g=await f.grant(b,{exp:Math.floor(f.now()/1000)});await assert.rejects(f.recover(b,g));once(f);});
test('replayed recovery grant rejected; fresh authorization retains same delivery',async()=>{const f=await bindingFixture(),first=await f.verify(),b=await f.installation(),g=await f.grant(b);await f.recover(b,g);await assert.rejects(f.recover(b,g),/RECOVERY_AUTHORIZATION_REPLAY/);const next=await f.recover(b,await f.grant(b));assert.equal(next.delivery_id,first.delivery_id);once(f);});
test('tampered recovery authorization rejected',async()=>{const f=await bindingFixture();await f.verify();const b=await f.installation(),g=await f.grant(b),parts=g.split('.');parts[1]=Buffer.from('{}').toString('base64url');await assert.rejects(f.recover(b,parts.join('.')));once(f);});
for(const name of ['revoked','Stripe','expired capability'])test('recovery rejects '+name,async()=>{const f=await bindingFixture();await f.verify();const b=await f.installation(),g=await f.grant(b);if(name==='revoked')f.store.state.subscriptions[0].status='revoked';if(name==='Stripe')f.store.state.listings[0].stripe_conflict=true;if(name==='expired capability'){const h=await sha256(b);f.store.state.capabilities.find(c=>c.token_hash===h).expires_at=iso(f.now());}await assert.rejects(f.recover(b,g));once(f);assert.equal(f.store.state.challenges.length,0);});
for(const n of [2,10]){
 test('same intent/transaction x'+n+' one commercial state',async()=>{const f=await bindingFixture(),r=await Promise.all(Array.from({length:n},()=>f.verify()));assert.equal(new Set(r.map(x=>x.delivery_id)).size,1);once(f);});
 test('cross installation x'+n+' all rejected',async()=>{const f=await bindingFixture(),b=await f.installation();const r=await Promise.allSettled(Array.from({length:n},()=>f.backend.verify(b,f.purchase.input)));assert.ok(r.every(x=>x.status==='rejected'));empty(f);});
 test('authorized recovery x'+n+' single grant consumption',async()=>{const f=await bindingFixture(),first=await f.verify(),b=await f.installation(),g=await f.grant(b);const r=await Promise.allSettled(Array.from({length:n},()=>f.recover(b,g)));assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(r.find(x=>x.status==='fulfilled').value.delivery_id,first.delivery_id);once(f);assert.equal(f.store.state.challenges.length,1);});
}
