import {verifyAndroidStripeBaseline} from './android-stripe-preservation-loader.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {execFileSync} from 'node:child_process';
import {integration,SharedNonceRepository,LocalAckSigner} from './node-integration-fixtures.mjs';
import {RestrictedReplayStore} from '../../supabase/functions/_shared/apple/restricted-replay-store.mjs';
import {NodeAppleVerifierClient,canonical,digest,FEATURED_POLICY} from '../../supabase/functions/_shared/apple/node-verifier-client.mjs';
import {verifyLocalDeliveryAck} from '../../supabase/functions/_shared/apple/delivery-ack.mjs';
import {recordNotification,processNotification} from '../../supabase/functions/_shared/apple/reconciliation.mjs';
import {uuid,iso,sha256} from '../../supabase/functions/_shared/apple/domain.mjs';
import {authenticate} from '/Users/yanier/Documents/abilene-apple-verifier/src/request-auth.mjs';
import {createService} from '/Users/yanier/Documents/abilene-apple-verifier/src/composition.mjs';
import {configure} from '/Users/yanier/Documents/abilene-apple-verifier/src/config.mjs';
import {InMemoryReplayStore} from '/Users/yanier/Documents/abilene-apple-verifier/src/replay-store.mjs';
import {compositionInput,responses,NOW} from './current-authentic-replay-fixture.mjs';
const empty=f=>{assert.equal(f.store.state.deliveries.length,0);assert.equal(f.store.state.transactions.length,0);assert.equal(f.store.state.entitlements.length,0);assert.equal(f.signer.calls,0);};
const changeFacts=(f,changes)=>Object.assign(f.verifier.evidence.get(f.purchase.input.transaction_jws),changes);
const newClient=(f,exchange,timeoutMs=15000)=>new NodeAppleVerifierClient({requestKey:f.config.requestKey,responseKey:f.config.responseKey,clock:f.now,exchange,timeoutMs});

test('M2M valid HMAC interoperability actual Node request-auth',async()=>{const f=await integration(),r=await f.verify();assert.equal(r.status,'delivered');assert.equal(f.hooks.calls,1);});
test('M2M bad request HMAC no acknowledgement',async()=>{const f=await integration();f.client.requestKey.fill(0);await assert.rejects(f.verify());empty(f);});
test('M2M fresh request ID and nonce on explicit retry',async()=>{const f=await integration();await f.verify();await f.verify();assert.equal(f.nonceRepo.entries.size,2);assert.equal(f.store.state.deliveries.length,1);});
test('Node unavailable closed',async()=>{const f=await integration();f.hooks.fail='unavailable';await assert.rejects(f.verify());empty(f);});
test('Node timeout closed',async()=>{const f=await integration();f.backend.appleVerifier=newClient(f,()=>new Promise(()=>{}),5);await assert.rejects(f.verify(),e=>e.code==='NODE_TIMEOUT');empty(f);});
test('bad response HMAC closed',async()=>{const f=await integration();f.hooks.alterResult=r=>({...r,signature:'0'.repeat(64)});await assert.rejects(f.verify());empty(f);});
test('unsigned Node response closed',async()=>{const f=await integration();f.hooks.alterResult=r=>({...r,signature:undefined});await assert.rejects(f.verify());empty(f);});
for(const [field,value]of [['requestId','wrong'],['requestBodyHash','0'.repeat(64)],['transactionHash','0'.repeat(64)],['appTransactionHash','0'.repeat(64)],['transactionIdentityHash','0'.repeat(64)],['originalTransactionIdentityHash','0'.repeat(64)],['bundleId','wrong.bundle'],['environment','Production'],['productId','wrong.product'],['subscriptionGroupId','wrong.group'],['policyVersion','wrong-policy'],['result','DELIVERED'],['failureCode','INTERNAL_ERROR'],['deliveryGranted',true],['finishCalled',true]])test('signed Node response wrong '+field,async()=>{const f=await integration();f.hooks.alterClaims=p=>({...p,[field]:value});await assert.rejects(f.verify());empty(f);});
test('signed response wrong audience',async()=>{const f=await integration();f.hooks.alterResult=r=>{const p=JSON.parse(r.body);p.audience='evil';return {...r,body:Buffer.from(canonical(p))};};await assert.rejects(f.verify());empty(f);});
test('expired response',async()=>{const f=await integration();f.hooks.alterClaims=p=>({...p,freshUntil:f.now()});await assert.rejects(f.verify());empty(f);});
test('future verifiedAt',async()=>{const f=await integration();f.hooks.alterClaims=p=>({...p,verifiedAt:f.now()+1});await assert.rejects(f.verify());empty(f);});
test('overlong response validity',async()=>{const f=await integration();f.hooks.alterClaims=p=>({...p,freshUntil:f.now()+60001});await assert.rejects(f.verify());empty(f);});
test('response facts absent closed',async()=>{const f=await integration();f.hooks.alterClaims=p=>({...p,verifiedFacts:null});await assert.rejects(f.verify());empty(f);});
test('response facts contradict summary',async()=>{const f=await integration();f.hooks.alterClaims=p=>({...p,verifiedFacts:Buffer.from(canonical({...JSON.parse(p.verifiedFacts),productId:'evil'})).toString()});await assert.rejects(f.verify());empty(f);});
test('Node response duplicate request context rejects',async()=>{const f=await integration();let saved;f.hooks.alterResult=r=>saved??(saved=r);await f.verify();await assert.rejects(f.verify());assert.equal(f.store.state.deliveries.length,1);});
test('nonce replay into actual Node authentication rejects',async()=>{const f=await integration();let authRequest;const orig=f.exchange;f.client.exchange=async r=>{authRequest??=r;return orig(authRequest);};await f.verify();await assert.rejects(f.verify());assert.equal(f.store.state.deliveries.length,1);});

test('shared replay first claim',async()=>{const r=new SharedNonceRepository(()=>1000);assert.equal(await new RestrictedReplayStore(r).claim('a'),true);});
test('shared replay duplicate',async()=>{const r=new SharedNonceRepository(()=>1000),a=new RestrictedReplayStore(r),b=new RestrictedReplayStore(r);await a.claim('a');assert.equal(await b.claim('a'),false);});
test('shared replay 32 concurrent instances exactly one',async()=>{const r=new SharedNonceRepository(()=>1000);const results=await Promise.all(Array.from({length:32},()=>new RestrictedReplayStore(r).claim('a')));assert.equal(results.filter(Boolean).length,1);});
test('shared replay TTL cleanup',async()=>{let n=1000;const r=new SharedNonceRepository(()=>n),s=new RestrictedReplayStore(r);await s.claim('a');n+=119999;assert.equal(await s.claim('a'),false);n++;assert.equal(await s.claim('a'),true);});
test('shared replay storage failure',async()=>{const r=new SharedNonceRepository(()=>1000);r.fail=true;await assert.rejects(new RestrictedReplayStore(r).claim('a'));});
test('shared replay no truthy bypass',async()=>await assert.rejects(new RestrictedReplayStore({claimAtomic:async()=> 'true'}).claim('a')));
test('shared replay rollback closed',async()=>{let n=1000;const r=new SharedNonceRepository(()=>n),s=new RestrictedReplayStore(r);await s.claim('a');n--;await assert.rejects(s.claim('b'));});
test('shared store unavailable prevents backend delivery',async()=>{const f=await integration();f.nonceRepo.fail=true;await assert.rejects(f.verify());empty(f);});

test('trusted buyer owns intent',async()=>{const f=await integration(),other=await f.buyer('other');await assert.rejects(f.backend.verify(other,f.purchase.input));empty(f);assert.equal(f.hooks.calls,0);});
for(const [name,changes]of [['appAccountToken',{app_account_token:uuid()}],['appTransactionId',{app_transaction_id:'other'}],['ownership',{ownership_type:'FAMILY_SHARED'}],['revocation',{revocation_date:'2026-01-01T00:00:00.000Z'}],['upgrade',{is_upgraded:true}],['expired',{expires_date:'2020-01-01T00:00:00.000Z'}],['future purchase',{purchase_date:'2099-01-01T00:00:00.000Z'}]])test('trusted binding rejects '+name,async()=>{const f=await integration();changeFacts(f,changes);await assert.rejects(f.verify());empty(f);});
test('listing unauthorized',async()=>{const f=await integration();f.store.state.grants=[];await assert.rejects(f.verify());empty(f);assert.equal(f.hooks.calls,0);});
test('listing ineligible',async()=>{const f=await integration();f.store.state.listings[0].status='rejected';await assert.rejects(f.verify());empty(f);});
test('Stripe conflict blocks Apple delivery',async()=>{const f=await integration();f.store.state.listings[0].stripe_conflict=true;await assert.rejects(f.verify());empty(f);});
test('untrusted client extra product rejected',async()=>{const f=await integration();await assert.rejects(f.backend.verify(f.token,{...f.purchase.input,product_id:'premium'}));empty(f);});
test('catalog group drift closes before Node',async()=>{const f=await integration();f.store.state.catalog[0].subscription_group_id='unconfigured';await assert.rejects(f.verify());empty(f);});
test('disabled catalog closed',async()=>{const f=await integration();f.store.state.catalog[0].enabled=false;await assert.rejects(f.verify());empty(f);});
test('installation revoked',async()=>{const f=await integration();f.store.state.installations[0].revoked_at=iso(f.now());await assert.rejects(f.verify());empty(f);});
test('idempotency key mismatch',async()=>{const f=await integration();f.purchase.input.idempotency_key=uuid();await assert.rejects(f.verify());empty(f);});

test('atomic fulfillment contains all required records',async()=>{const f=await integration();await f.verify();for(const k of ['transactions','deliveries','subscriptions','assignments','entitlements'])assert.equal(f.store.state[k].length,1,k);assert.equal(f.store.state.intents[0].status,'completed');});
test('same transaction twice one fulfillment',async()=>{const f=await integration();const a=await f.verify(),b=await f.verify();assert.equal(b.status,'already_delivered');assert.equal(a.delivery_id,b.delivery_id);assert.equal(f.store.state.deliveries.length,1);});
test('concurrent same transaction one fulfillment',async()=>{const f=await integration();const rs=await Promise.all(Array.from({length:8},()=>f.verify()));assert.equal(new Set(rs.map(r=>r.delivery_id)).size,1);assert.equal(f.store.state.deliveries.length,1);assert.equal(f.store.state.entitlements.length,1);});
test('duplicate inconsistent transaction rejected',async()=>{const f=await integration();await f.verify();changeFacts(f,{expires_date:iso(f.now()+1234567)});await assert.rejects(f.verify());assert.equal(f.store.state.deliveries.length,1);assert.equal(f.signer.calls,1);});
test('DB before commit no delivery/ack',async()=>{const f=await integration();f.store.crashBefore=true;await assert.rejects(f.verify());empty(f);});
test('atomic candidate partial writes discarded on failure',async()=>{const f=await integration();const before=structuredClone(f.store.state);f.store.compareAndSwap=async(_version,candidate)=>{assert.equal(candidate.deliveries.length,1);const privateStaging=structuredClone(candidate);privateStaging.deliveries=[];throw Error('mid-operation rollback');};await assert.rejects(f.verify());assert.deepEqual(f.store.state,before);assert.equal(f.signer.calls,0);});
test('commit then response lost recover existing delivery',async()=>{const f=await integration();f.store.crashAfter=true;await assert.rejects(f.verify());assert.equal(f.store.state.deliveries.length,1);assert.equal(f.signer.calls,0);const r=await f.verify();assert.equal(r.status,'already_delivered');assert.equal((await f.gate(r)).finishAllowed,true);assert.equal(f.store.state.deliveries.length,1);});
test('ack signer failure after commit recover without repeat delivery',async()=>{const f=await integration(),sign=f.signer.sign.bind(f.signer);f.signer.sign=async()=>{throw Error('signer unavailable');};await assert.rejects(f.verify());assert.equal(f.store.state.deliveries.length,1);f.signer.sign=sign;const r=await f.verify();assert.equal(r.status,'already_delivered');assert.equal((await f.gate(r)).finishAllowed,true);});
test('freshness checked again inside CAS operation',async()=>{const f=await integration(),orig=f.store.read.bind(f.store);let reads=0;f.store.read=async()=>{if(++reads===2)f.advance(60000);return orig();};await assert.rejects(f.verify());empty(f);});
test('expiry during commit emits no acknowledgement',async()=>{const f=await integration(),orig=f.store.compareAndSwap.bind(f.store);f.store.compareAndSwap=async(v,s)=>{const r=await orig(v,s);f.advance(60000);return r;};await assert.rejects(f.verify());assert.equal(f.signer.calls,0);});
test('revoked delivered chain cannot reissue ack',async()=>{const f=await integration();await f.verify();f.store.state.subscriptions[0].status='revoked';await assert.rejects(f.verify());assert.equal(f.signer.calls,1);});

test('ack valid after commit enables contractual gate',async()=>{const f=await integration(),r=await f.verify();assert.equal((await f.gate(r)).finishAllowed,true);});
for(const [k,v]of [['transactionId','999'],['buyer_id','wrong'],['installation_id','wrong'],['installation_key_id','wrong'],['delivery_id','wrong'],['productId','wrong'],['environment','Production']])test('ack rejects wrong '+k,async()=>{const f=await integration(),r=await f.verify();assert.equal((await f.gate(r,{[k]:v})).finishAllowed,false);});
test('ack tamper',async()=>{const f=await integration(),r=await f.verify(),parts=r.confirmation.signed_jws.split('.');const p=JSON.parse(Buffer.from(parts[1],'base64url'));p.transactionId='999';parts[1]=Buffer.from(JSON.stringify(p)).toString('base64url');r.confirmation.signed_jws=parts.join('.');assert.equal((await f.gate(r)).finishAllowed,false);});
test('ack expired',async()=>{const f=await integration(),r=await f.verify();f.advance(300000);assert.equal((await f.gate(r)).finishAllowed,false);});
test('ack reissue different ID same durable delivery',async()=>{const f=await integration(),a=await f.verify(),b=await f.verify();const ga=await f.gate(a),gb=await f.gate(b);assert.equal(ga.deliveryId,gb.deliveryId);assert.notEqual(ga.ackId,gb.ackId);});
test('missing ack does not allow finish',async()=>assert.equal((await verifyLocalDeliveryAck(null,{},null,0)).finishAllowed,false));
test('Node verified response is not delivery ack',async()=>{const f=await integration();assert.equal((await verifyLocalDeliveryAck({kind:'VERIFIED_FOR_FULFILLMENT_EVALUATION'}, {},null,0)).finishAllowed,false);});

async function renewal(f){const t={...f.purchase.t,transaction_id:'202',purchase_date:iso(f.now()+1000),expires_date:iso(f.now()+172800000)};return {bundle_id:t.bundle_id,environment:t.environment,notification_uuid:uuid(),notification_type:'DID_RENEW',signed_date:f.now()+1000,original_transaction_id:t.original_transaction_id,transaction_id:t.transaction_id,product_id:t.product_id,app_account_token:t.app_account_token,app_transaction_id:t.app_transaction_id,period_start:t.purchase_date,period_end:t.expires_date,transaction:t};}
async function processSynthetic(f,e){return f.backend.change((s,now)=>{const n=recordNotification(s,e,'DIAGNOSTIC-EVENT-HASH',now);return processNotification(s,n,now);});}
test('renewal distinct transaction same lineage processed',async()=>{const f=await integration();await f.verify();const e=await renewal(f);await processSynthetic(f,e);assert.equal(f.store.state.transactions.length,2);assert.equal(f.store.state.deliveries.length,2);assert.equal(f.store.state.subscriptions.length,1);});
test('renewal invents no intent or assignment',async()=>{const f=await integration();await f.verify();const before=structuredClone(f.store.state.assignments);await processSynthetic(f,await renewal(f));assert.deepEqual(f.store.state.assignments,before);assert.equal(f.store.state.intents.length,1);assert.equal(f.store.state.entitlements.length,1);});
test('duplicate renewal event idempotent',async()=>{const f=await integration();await f.verify();const e=await renewal(f);await processSynthetic(f,e);await processSynthetic(f,e);assert.equal(f.store.state.notifications.length,1);assert.equal(f.store.state.transactions.length,2);});
test('renewal wrong buyer quarantined',async()=>{const f=await integration();await f.verify();const e=await renewal(f);e.app_account_token=uuid();const n=await processSynthetic(f,e);assert.equal(n.status,'quarantined');assert.equal(f.store.state.transactions.length,1);});
test('unknown renewal lineage does not create assignment',async()=>{const f=await integration();await f.verify();const e=await renewal(f);e.original_transaction_id='9999';const n=await processSynthetic(f,e);assert.equal(n.status,'retry');assert.equal(f.store.state.assignments.length,1);});
test('Node notification route remains unconfigured',async()=>{const f=await integration();await assert.rejects(f.backend.notification('not-real-notification'),e=>e.code==='NODE_NOTIFICATIONS_NOT_CONFIGURED');});

test('authentic Node response consumed locally without fulfillment',async()=>{const clock=()=>NOW,replay=new InMemoryReplayStore({clock});const c=configure({requestKey:Buffer.from(crypto.getRandomValues(new Uint8Array(32))),responseKey:Buffer.from(crypto.getRandomValues(new Uint8Array(32))),rootDer:compositionInput.rootDer,clock,replayStore:replay,ocspLoader:async h=>responses[h.index]});const service=createService(c);const client=new NodeAppleVerifierClient({requestKey:c.requestKey,responseKey:c.responseKey,clock,exchange:r=>service.handle({...r,body:Buffer.from(r.body)})});const context={intentId:uuid(),...FEATURED_POLICY};const t=await client.verifyTransaction(compositionInput.transactionJws,compositionInput.appTransactionJws,context);assert.equal(t.product_id,FEATURED_POLICY.product);client.assertFresh(t,NOW,context);});
test('Android Stripe sources match independent preservation baseline',()=>{assert.equal(verifyAndroidStripeBaseline(process.cwd()),65);});
test('live entrypoints remain unconfigured',()=>{for(const fn of ['apple-prepare-purchase','apple-verify-purchase','apple-notifications'])assert.match(fs.readFileSync(`supabase/functions/${fn}/index.ts`,'utf8'),/handler\('[a-z]+'\)/);});
test('delayed atomic publication past Node deadline rolls back all records',async()=>{const f=await integration(),before=structuredClone(f.store.state);f.store.beforePublish=async()=>{f.advance(60001);};await assert.rejects(f.verify());assert.deepEqual(f.store.state,before);assert.equal(f.signer.calls,0);});
test('Postgres repository selects guarded CAS and carries deadline',async()=>{const {PostgresAppleRepository}=await import('../../supabase/functions/_shared/apple/repository.mjs');let called;const repo=new PostgresAppleRepository(async(name,args)=>{called={name,args};return {data:true,error:null};});await repo.compareAndSwap(2,{}, {notAfter:1800000000000});assert.equal(called.name,'apple_ledger_compare_and_swap_verified');assert.equal(called.args.verification_not_after,'2027-01-15T08:00:00.000Z');});
test('Postgres guard failure is not successful commit',async()=>{const {PostgresAppleRepository}=await import('../../supabase/functions/_shared/apple/repository.mjs');const repo=new PostgresAppleRepository(async()=>({error:{message:'expired'}}));await assert.rejects(repo.compareAndSwap(1,{}, {notAfter:1800000000000}));});
for(const [field,value]of [['audience','wrong-audience'],['keyId','wrong-key']])test('valid MAC but wrong response '+field+' rejects',async()=>{const f=await integration();const {hmac}=await import('../../supabase/functions/_shared/apple/node-verifier-client.mjs');f.hooks.alterResult=async r=>{const p={...JSON.parse(r.body),[field]:value},body=Buffer.from(canonical(p));return {...r,body,signature:await hmac(f.config.responseKey,body)};};await assert.rejects(f.verify());empty(f);});
test('ack signer sees published durable candidate only',async()=>{const f=await integration(),sign=f.signer.sign.bind(f.signer);f.signer.sign=async claims=>{assert.ok(f.store.state.deliveries.some(d=>d.id===claims.delivery_id));assert.equal(f.store.state.intents[0].status,'completed');assert.equal(f.store.state.entitlements.length,1);return sign(claims);};await f.verify();});
test('app retry with recreated client recovers same delivery',async()=>{const f=await integration();const first=await f.verify();f.backend.appleVerifier=newClient(f,f.exchange);const recovered=await f.verify();assert.equal(recovered.delivery_id,first.delivery_id);assert.equal(recovered.status,'already_delivered');assert.equal(f.store.state.deliveries.length,1);});
