// Explicit opt-in integration runner. No packages, remote connections, or memory repository as SUT.
import {spawn} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
import {setup} from './fixtures.mjs';
import {PostgresAppleRepository} from '../../supabase/functions/_shared/apple/repository.mjs';
import {uuid,iso,BUNDLE} from '../../supabase/functions/_shared/apple/domain.mjs';
const docker='/Applications/Docker.app/Contents/Resources/bin/docker';
const container='abilene-phase38-postgres',db='abilene_apple_phase37_test';
const evidence='/private/tmp/abilene-phase39';mkdirSync(evidence,{recursive:true});
const migration=readFileSync(new URL('../../supabase/migrations/202609080001_apple_iap_ledger.sql',import.meta.url),'utf8');
const fixture=readFileSync(new URL('./phase39-fixture.sql',import.meta.url),'utf8');
const q=x=>"'"+String(x).replaceAll("'","''")+"'";
let serial=0;const results=[];
function command(args,input='') {return new Promise((resolve,reject)=>{const p=spawn(docker,['--context','desktop-linux',...args]);let out='',err='';p.stdout.on('data',c=>out+=c);p.stderr.on('data',c=>err+=c);p.on('error',reject);p.on('close',code=>code?reject(Object.assign(new Error(err),{out,code})):resolve(out.trim()));p.stdin.end(input);});}
async function sql(text,role='postgres',database=db){assert.ok(['postgres',db].includes(database));assert.ok(['postgres','anon','authenticated','service_role'].includes(role));return command(['exec','-i',container,'sh','-c',`PGPASSWORD="$POSTGRES_PASSWORD" psql -X -qAt -w -h 127.0.0.1 -U postgres -d ${database} -v ON_ERROR_STOP=1 -v VERBOSITY=verbose`],`SET statement_timeout='15s'; SET lock_timeout='8s'; SET ROLE ${role};\n${text}`);}
async function guard(){const c=JSON.parse(await command(['inspect','--format','{{json .}}',container]));assert.equal(c.Name,'/'+container);assert.equal(c.State.Status,'running');assert.deepEqual(c.NetworkSettings.Ports,{'5432/tcp':[{HostIp:'127.0.0.1',HostPort:'49447'}]});assert.equal(c.Mounts.length,0);const endpoint=await command(['context','inspect','desktop-linux','--format','{{.Endpoints.docker.Host}}']);assert.equal(endpoint,'unix:///Users/yanier/.docker/run/docker.sock');const uri=`postgresql://postgres@127.0.0.1:49447/${db}`;assert.ok(!/ymgiwjuhgvfexitynmtb|supabase\.co/.test(uri));assert.equal(await sql('select current_database()'),db);console.log('GUARD PASS local socket, container, DB, loopback and no host mounts');}
async function install(recreate=false){if(recreate){await sql(`DROP DATABASE ${db} WITH (FORCE);`, 'postgres','postgres');await sql(`CREATE DATABASE ${db};`,'postgres','postgres');}else assert.equal(await sql("select count(*) from information_schema.tables where table_schema='public'"),'0');await sql(fixture);const out=await command(['exec','-i',container,'sh','-c',`PGPASSWORD="$POSTGRES_PASSWORD" psql -X -w -h 127.0.0.1 -U postgres -d ${db} -v ON_ERROR_STOP=1`],migration);writeFileSync(`${evidence}/apply-${++serial}.log`,out);assert.match(out,/BEGIN/);assert.match(out,/COMMIT/);console.log('INSTALL PASS',serial);}
const repo=new PostgresAppleRepository(async(name,args)=>{try{return {data:JSON.parse(await sql(name==='apple_ledger_snapshot'?'select public.apple_ledger_snapshot();':`select to_jsonb(public.apple_ledger_compare_and_swap(${args.expected_version},${q(JSON.stringify(args.next_state))}::jsonb));`,'service_role'))};}catch(e){writeFileSync(`${evidence}/last-rpc-error.txt`,e.message);throw e;}});
const read=()=>repo.read();
async function seed(state){for(const l of state.listings??[])await sql(`insert into public.${{business:'business_submissions',job:'job_listings',rental:'rental_listings'}[l.listing_type]}(id,status,payment_status) values(${q(l.listing_id)},${q(l.status)},${l.stripe_conflict?q('paid'):'null'}) on conflict(id) do nothing;`);const s=await read();assert.equal(await repo.compareAndSwap(s.version,state),true);}
async function ready(deliver=false){await install(true);const f=await setup();f.token=await f.buyer();f.list=await f.listing(f.token);await seed(f.store.state);f.backend.store=repo;if(deliver){f.p=await purchase(f);f.result=await f.backend.verify(f.token,f.p.input);}return f;}
async function listing(f,kind='business',status='approved'){const s=await read(),id=uuid();await sql(`insert into public.${{business:'business_submissions',job:'job_listings',rental:'rental_listings'}[kind]}(id,status) values(${q(id)},${q(status)});`);s.state.grants.push({id:uuid(),buyer_id:s.state.buyers[0].id,environment:'Sandbox',listing_type:kind,listing_id:id,expires_at:iso(f.now()+86400000),revoked_at:null,created_at:iso(f.now())});assert.ok(await repo.compareAndSwap(s.version,s.state));return {listing_type:kind,listing_id:id,requested_plan:'featured',idempotency_key:uuid()};}
let tx=2000;
async function purchase(f,l=f.list,overrides={}){const p=await f.backend.prepare(f.token,l);await f.backend.markPurchasing(f.token,p.purchase_intent_id);const s=await read(),b=s.state.buyers[0],id=String(++tx);const t={bundle_id:BUNDLE,environment:'Sandbox',transaction_id:id,original_transaction_id:id,product_id:p.product_id,app_account_token:b.app_account_token,app_transaction_id:b.app_transaction_id,subscription_group_id:'TEST-GROUP-'+p.slot_number,purchase_date:iso(f.now()),expires_date:iso(f.now()+86400000),revocation_date:null,revocation_reason:null,ownership_type:'PURCHASED',is_upgraded:false,...overrides};return {t,input:{purchase_intent_id:p.purchase_intent_id,transaction_jws:f.verifier.register(t),app_transaction_jws:'TEST-APP-PROOF',idempotency_key:l.idempotency_key}};}
function event(f,type,extra={}){return {bundle_id:BUNDLE,environment:'Sandbox',notification_uuid:uuid(),notification_type:type,subtype:null,signed_date:f.now()+1,original_transaction_id:f.p.t.original_transaction_id,transaction_id:f.p.t.transaction_id,product_id:f.p.t.product_id,app_account_token:f.p.t.app_account_token,app_transaction_id:f.p.t.app_transaction_id,period_start:f.p.t.purchase_date,period_end:f.p.t.expires_date,transaction:f.p.t,...extra};}
async function test(name,fn){try{await fn();results.push({name,status:'pass'});console.log('PASS',name);}catch(e){results.push({name,status:'fail',error:e.message});console.log('FAIL',name,e.message);throw e;}finally{writeFileSync(`${evidence}/results.json`,JSON.stringify(results,null,2));}}
async function denied(text,role,pattern=/42501|permission denied/){await assert.rejects(sql(text,role),pattern);}
async function atomicReject(text,pattern){await assert.rejects(sql('begin;\n'+text+'\nrollback;'),pattern);}
async function main(){await guard();if(process.argv.includes('--fresh'))await install(true);else await install();
await test('catalogue: 15 RLS tables, constraints, indexes, triggers and function metadata',async()=>{
 const tables=JSON.parse(await sql("select json_agg(json_build_object('name',c.relname,'rls',c.relrowsecurity,'owner',pg_get_userbyid(c.relowner))) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and (c.relname like 'apple_%' or c.relname='listing_promotion_entitlements')"));assert.equal(tables.length,15);assert.ok(tables.every(t=>t.rls&&t.owner==='postgres'));
 const queries={columns:"select table_name,column_name,data_type,is_nullable from information_schema.columns where table_schema='public' order by 1,ordinal_position",constraints:"select conrelid::regclass,conname,contype,pg_get_constraintdef(oid) from pg_constraint where connamespace='public'::regnamespace order by 1,2",indexes:"select tablename,indexname,indexdef from pg_indexes where schemaname='public'",triggers:"select tgrelid::regclass,tgname,pg_get_triggerdef(oid) from pg_trigger where not tgisinternal and tgrelid in (select oid from pg_class where relnamespace='public'::regnamespace)",functions:"select proname,pg_get_userbyid(proowner),prosecdef,proconfig,proacl from pg_proc where pronamespace='public'::regnamespace",policies:"select * from pg_policies where schemaname='public'",grants:"select * from information_schema.role_table_grants where table_schema='public'",schema:"select nspname,nspacl from pg_namespace where nspname='public'"};for(const [k,v]of Object.entries(queries))writeFileSync(`${evidence}/${k}.txt`,await sql(v));
 assert.equal(await sql("select count(*) from pg_policies where schemaname='public'"),'0');assert.equal(await sql("select count(*) from pg_proc where pronamespace='public'::regnamespace and prosecdef and proconfig @> array['search_path=pg_catalog, public, pg_temp']"),'2');assert.equal(await sql("select count(*) from pg_constraint where contype='p' and connamespace='public'::regnamespace"),'18');
});
await test('roles: anon/authenticated/service_role denied direct DML, DELETE, TRUNCATE; RPC only service',async()=>{for(const role of ['anon','authenticated','service_role']){for(const stmt of ['select * from apple_buyers','select * from apple_transactions','insert into apple_purchase_intents default values','update listing_promotion_entitlements set plan=\'premium\'','delete from apple_transactions','truncate apple_ledger_revision','insert into apple_deliveries default values','update apple_slot_occupancies set slot_number=1','update apple_subscriptions set status=\'active\''])await denied(stmt,role);await denied('create table public.forged(id int)',role);if(role!=='service_role')await denied('select apple_ledger_snapshot()',role);}assert.equal((await read()).version,0);});
await test('real backend preparation, delivery and exact replay after SQL round trip',async()=>{const f=await ready(true);const before=await read();const r=await f.backend.verify(f.token,f.p.input);assert.equal(r.status,'already_delivered');const after=await read();assert.deepEqual(after.state.transactions,before.state.transactions);assert.deepEqual(after.state.entitlements,before.state.entitlements);assert.equal(after.state.deliveries.length,1);});
await test('idempotency: same request, changed request, chain and unique delivery',async()=>{const f=await ready();const a=await f.backend.prepare(f.token,f.list),b=await f.backend.prepare(f.token,f.list);assert.equal(a.purchase_intent_id,b.purchase_intent_id);await assert.rejects(f.backend.prepare(f.token,{...f.list,requested_plan:'premium'}),/IDEMPOTENCY_CONFLICT/);let s=await read();assert.equal(s.state.intents.length,1);assert.equal(s.state.slots.length,1);f.p=await purchase(f,await listing(f));await f.backend.verify(f.token,f.p.input);s=await read();for(const table of ['apple_transactions','apple_subscriptions','apple_deliveries'])await atomicReject(`insert into ${table} select * from ${table};`,/23505/);});
await test('immutable bindings and DELETE/TRUNCATE even through privileged SQL',async()=>{await ready(true);const attacks=[['apple_buyers','id=gen_random_uuid()'],['apple_buyers','app_account_token=gen_random_uuid()'],['apple_buyers',"app_transaction_id='changed'"],['apple_buyers',"bundle_id='other'"],['apple_buyers',"environment='Production'"],['apple_subscriptions',"original_transaction_id='changed'"],['apple_subscriptions','buyer_id=gen_random_uuid()'],['apple_subscription_assignments','listing_id=gen_random_uuid()'],['apple_subscription_assignments','purchase_intent_id=gen_random_uuid()'],['apple_transactions',"transaction_id='changed'"],['apple_transactions','assignment_id=gen_random_uuid()'],['apple_slot_occupancies','slot_number=10'],['apple_deliveries','assignment_id=gen_random_uuid()']];for(const [t,set]of attacks)await atomicReject(`update ${t} set ${set};`,/IMMUTABLE_APPLE_BINDING/);for(const t of ['apple_buyers','apple_purchase_intents','apple_subscriptions','apple_subscription_assignments','apple_transactions','apple_deliveries','apple_slot_occupancies','listing_promotion_entitlements']){await atomicReject(`delete from ${t};`,/APPLE_HISTORY_DELETE_FORBIDDEN/);await atomicReject(`truncate ${t} cascade;`,/APPLE_HISTORY_DELETE_FORBIDDEN/);}});
await test('known identifiers grant no caller privileges or execute rights',async()=>{const s=await read();for(const r of ['anon','authenticated']){for(const col of ['app_account_token','app_transaction_id','id'])await denied(`select * from apple_buyers where ${col}=${q(s.state.buyers[0][col])}`,r);await denied(`select * from apple_transactions where transaction_id=${q(s.state.transactions[0].transaction_id)} or original_transaction_id=${q(s.state.transactions[0].original_transaction_id)}`,r);await denied(`select apple_ledger_compare_and_swap(${s.version},${q(JSON.stringify(s.state))})`,r);}assert.equal(await sql("select count(*) from pg_proc p, lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where p.pronamespace='public'::regnamespace and a.grantee=0 and a.privilege_type='EXECUTE'"),'0');});
await test('A/B concurrent same listing and double tap use real CAS connections',async()=>{const f=await ready();const run=async(inputs)=>{const original=f.backend.store;let reads=0,release;const gate=new Promise(r=>release=r);f.backend.store={async read(){const s=await repo.read();if(++reads<=2){if(reads===2)release();await gate;}return s;},compareAndSwap:(...a)=>repo.compareAndSwap(...a)};try{return await Promise.allSettled(inputs.map(x=>f.backend.prepare(f.token,x)));}finally{f.backend.store=original;}};const a=await run([f.list,{...f.list,idempotency_key:uuid()}]);assert.equal(a.filter(x=>x.status==='fulfilled').length,1);assert.match(a.find(x=>x.status==='rejected').reason.message,/APPLE_CONFLICT/);const l=await listing(f);const b=await run([l,l]);assert.equal(b[0].value.purchase_intent_id,b[1].value.purchase_intent_id);assert.equal((await read()).state.slots.length,2);console.log('A outcomes',a.map((x,i)=>[i,x.status,x.reason?.message]));console.log('B one logical intent',b[0].value.purchase_intent_id);});
await test('C/F last slot concurrent and eleventh request across Business/Job/Rental',async()=>{const f=await ready();for(let i=0;i<9;i++)await f.backend.prepare(f.token,await listing(f,['business','job','rental'][i%3]));const a=await listing(f),b=await listing(f);const r=await Promise.allSettled([f.backend.prepare(f.token,a),f.backend.prepare(f.token,b)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.match(r.find(x=>x.status==='rejected').reason.message,/NO_SLOT_AVAILABLE/);const before=await read();await assert.rejects(f.backend.prepare(f.token,await listing(f)),/NO_SLOT_AVAILABLE/);assert.deepEqual((await read()).state.slots,before.state.slots);assert.equal(before.state.slots.length,10);console.log('C/F outcomes',r.map((x,i)=>[i,x.status,x.reason?.message]));});
await test('D simultaneous delivery persists exactly once',async()=>{const f=await ready();const p=await purchase(f);const r=await Promise.all([f.backend.verify(f.token,p.input),f.backend.verify(f.token,p.input)]);assert.equal(r[0].delivery_id,r[1].delivery_id);const s=await read();assert.equal(s.state.transactions.length,1);assert.equal(s.state.deliveries.length,1);assert.equal(s.state.entitlements.length,1);console.log('D outcomes',r.map(x=>x.status));});
await test('E independent sessions: lock wait and stale CAS false',async()=>{const s=await read();const query=`select apple_ledger_compare_and_swap(${s.version},${q(JSON.stringify(s.state))}::jsonb);`;const a=sql(`begin; select pg_backend_pid(); select revision from apple_ledger_revision for update; select pg_sleep(2); ${query} commit;`);await new Promise(r=>setTimeout(r,250));const b=sql(`set application_name='phase39-cas-b'; begin; select pg_backend_pid(); ${query} commit;`);await new Promise(r=>setTimeout(r,250));assert.equal(await sql("select wait_event_type from pg_stat_activity where application_name='phase39-cas-b'"),'Lock');const r=await Promise.all([a,b]);assert.match(r[0],/\nt$/);assert.match(r[1],/\nf$/);assert.notEqual(r[0].split('\n')[0],r[1].split('\n')[0]);assert.equal((await read()).version,s.version+1);console.log('E backend PID/winner',r);});
await test('rollback after intent/slot/transaction and before entitlement/delivery/revision',async()=>{const f=await ready();f.p=await purchase(f);const before=await read();await f.backend.verify(f.token,f.p.input);const complete=await read();await install(true);await seed(before.state);const start=await read();for(const stage of ['intents','slots','transactions','entitlements','deliveries','revision']){const target={intents:'apple_purchase_intents',slots:'apple_slot_occupancies',transactions:'apple_transactions',entitlements:'listing_promotion_entitlements',deliveries:'apple_deliveries',revision:'apple_ledger_revision'}[stage];const timing=['entitlements','deliveries','revision'].includes(stage)?'before':'after';const fault=`create function public.phase39_fault() returns trigger language plpgsql as $$ begin raise exception 'PHASE39_INJECTED'; end $$; create trigger phase39_fault ${timing} insert or update on ${target} for each row execute function public.phase39_fault();`;await assert.rejects(sql(`begin; ${fault} select apple_ledger_compare_and_swap(${start.version},${q(JSON.stringify(complete.state))}); commit;`),/PHASE39_INJECTED/);assert.deepEqual(await read(),start);assert.equal(await sql("select count(*) from pg_proc where proname='phase39_fault'"),'0');}assert.equal(await repo.compareAndSwap(start.version-1,complete.state),false);assert.deepEqual(await read(),start);assert.ok(await repo.compareAndSwap(start.version,complete.state));assert.equal((await read()).state.deliveries.length,1);});
await test('listings permissions, eligibility, Stripe, disabled catalogue and forged input',async()=>{const f=await ready();await assert.rejects(f.backend.prepare(f.token,{...f.list,listing_id:uuid()}),/LISTING_NOT_FOUND/);const hidden=await listing(f,'job','hidden');await assert.rejects(f.backend.prepare(f.token,hidden),/LISTING_INELIGIBLE/);for(const k of ['buyer_id','product_id','slot_number'])await assert.rejects(f.backend.prepare(f.token,{...f.list,[k]:'forged'}),/INVALID_INPUT/);await assert.rejects(f.backend.prepare(f.token,{...f.list,requested_plan:'forged'}),/INVALID_PLAN/);let s=await read();s.state.grants[0].expires_at=iso(0);await repo.compareAndSwap(s.version,s.state);await assert.rejects(f.backend.prepare(f.token,f.list),/LISTING_UNAUTHORIZED/);const l=await listing(f);await sql(`update business_submissions set payment_status='paid' where id=${q(l.listing_id)}`);await assert.rejects(f.backend.prepare(f.token,l),/STRIPE_CONFLICT/);const noGrant=uuid();await sql(`insert into business_submissions(id,status) values(${q(noGrant)},'approved')`);await assert.rejects(f.backend.prepare(f.token,{...f.list,listing_id:noGrant}),/LISTING_UNAUTHORIZED/);s=await read();s.state.catalog.forEach(p=>p.enabled=false);await repo.compareAndSwap(s.version,s.state);await assert.rejects(f.backend.prepare(f.token,await listing(f)),/CATALOG_NOT_CONFIGURED/);});
for(const [type,expected,extra]of [['SUBSCRIBED','active',{}],['DID_RENEW','active',{}],['DID_CHANGE_RENEWAL_STATUS','active_nonrenewing',{auto_renew_enabled:false}],['DID_FAIL_TO_RENEW','grace',{grace_period_expires_at:iso(1800003600000)}],['GRACE_PERIOD_EXPIRED','billing_retry',{}],['EXPIRED','expired',{}],['REFUND','revoked',{}],['REVOKE','revoked',{}]])await test('persisted notification '+type,async()=>{const f=await ready(true);const e=event(f,type,extra);if(type==='DID_RENEW'){e.transaction={...f.p.t,transaction_id:String(++tx),purchase_date:iso(f.now()+1),expires_date:iso(f.now()+172800000)};e.transaction_id=e.transaction.transaction_id;e.period_start=e.transaction.purchase_date;e.period_end=e.transaction.expires_date;}const h=f.verifier.register(e);await f.backend.notification(h);const before=await read();await f.backend.notification(h);const s=await read();assert.equal(s.state.subscriptions[0].status,expected);assert.equal(s.state.notifications.length,1);assert.equal(s.state.notifications[0].status,'processed');assert.deepEqual(s.state.entitlements,before.state.entitlements);assert.equal(s.state.deliveries.length,type==='DID_RENEW'?2:1);});
await test('notifications before verify, unknown chain/buyer, wrong environment and late refund',async()=>{const f=await ready();f.p=await purchase(f);const h=f.verifier.register(event(f,'SUBSCRIBED'));assert.equal((await f.backend.notification(h)).status,'retry');await f.backend.verify(f.token,f.p.input);await f.backend.reconciliation(f.token);assert.equal((await read()).state.notifications[0].status,'processed');const unknown=event(f,'SUBSCRIBED',{original_transaction_id:'999999999',app_account_token:uuid()});assert.equal((await f.backend.notification(f.verifier.register(unknown))).status,'retry');const absent=event(f,'SUBSCRIBED',{app_account_token:uuid()});assert.equal((await f.backend.notification(f.verifier.register(absent))).status,'quarantined');for(const environment of ['Production','Xcode'])await assert.rejects(f.backend.notification(f.verifier.register(event(f,'REFUND',{environment}))),/ENVIRONMENT_DISABLED/);await f.backend.notification(f.verifier.register(event(f,'DID_CHANGE_RENEWAL_STATUS',{auto_renew_enabled:false,signed_date:f.now()+3})));assert.equal((await f.backend.notification(f.verifier.register(event(f,'DID_CHANGE_RENEWAL_STATUS',{auto_renew_enabled:true,signed_date:f.now()+2})))).status,'quarantined');await f.backend.notification(f.verifier.register(event(f,'REFUND',{signed_date:f.now()+1})));assert.equal((await read()).state.subscriptions[0].status,'reconciliation');});

await test('same IDs in Sandbox/Production and forbidden cross-environment associations',async()=>{await ready(true);const sandbox=(await read()).state;const production=structuredClone(sandbox);const ids=new Map();for(const k of ['buyers','installations','capabilities','grants','intents','subscriptions','assignments','entitlements','deliveries'])for(const row of production[k]){for(const field of ['id','installation_id','app_account_token'])if(row[field]&&!ids.has(row[field]))ids.set(row[field],uuid());}function remap(x){if(Array.isArray(x))return x.map(remap);if(x&&typeof x==='object')return Object.fromEntries(Object.entries(x).map(([k,v])=>[k,k==='environment'?'Production':k==='token_hash'?'b'.repeat(64):remap(v)]));return ids.get(x)??x;}const p=remap(production);const tables={buyers:'apple_buyers',installations:'apple_installations',capabilities:'apple_session_capabilities',grants:'apple_listing_authorizations',intents:'apple_purchase_intents',subscriptions:'apple_subscriptions',assignments:'apple_subscription_assignments',slots:'apple_slot_occupancies',transactions:'apple_transactions',notifications:'apple_notification_events',entitlements:'listing_promotion_entitlements',deliveries:'apple_deliveries'};const insert=(t,rows)=>`insert into public.${t} select * from jsonb_populate_recordset(null::public.${t},${q(JSON.stringify(rows))});`;await sql('begin;'+Object.entries(tables).map(([k,t])=>insert(t,p[k])).join('\n')+'commit;');assert.equal(await sql('select count(*) from apple_transactions'),'2');assert.equal(await sql('select count(distinct transaction_id) from apple_transactions'),'1');assert.equal(await sql('select count(distinct original_transaction_id) from apple_subscriptions'),'1');assert.equal(await sql('select count(distinct app_transaction_id) from apple_buyers'),'1');assert.equal((await read()).state.buyers.length,1);assert.equal(await sql('select count(distinct listing_id) from apple_slot_occupancies'),'1');
const cross=[['apple_transactions',{...p.transactions[0],transaction_id:'777001',subscription_id:sandbox.subscriptions[0].id}],['apple_transactions',{...sandbox.transactions[0],transaction_id:'777002',assignment_id:p.assignments[0].id}],['apple_challenges',{id:uuid(),nonce_hash:'c'.repeat(64),installation_id:sandbox.installations[0].installation_id,environment:'Production',purpose:'test',request_digest:'synthetic',expires_at:iso(1800000010000),consumed_at:null,created_at:iso(1800000000000)}]];for(const [t,row]of cross)await atomicReject(insert(t,[row]),/23503/);
const freshSub={...sandbox.subscriptions[0],id:uuid(),slot_number:2,product_id:sandbox.subscriptions[0].product_id.replace('slot01','slot02'),original_transaction_id:'777000'};await atomicReject(insert('apple_subscriptions',[freshSub])+insert('apple_subscription_assignments',[{...p.assignments[0],id:uuid(),subscription_id:freshSub.id,slot_number:2}]),/23503/);
await atomicReject(insert('apple_transactions',[{...p.transactions[0],transaction_id:'777003'}])+insert('apple_deliveries',[{...p.deliveries[0],id:uuid(),transaction_id:'777003',assignment_id:sandbox.assignments[0].id}]),/23503/);
await atomicReject(insert('apple_transactions',[{...sandbox.transactions[0],transaction_id:'777004'}])+insert('apple_deliveries',[{...sandbox.deliveries[0],id:uuid(),transaction_id:'777004',purchase_intent_id:p.intents[0].id}]),/23503/);
await atomicReject(insert('apple_notification_events',[{id:uuid(),environment:'Production',notification_uuid:'cross',notification_type:'REFUND',subtype:null,signed_date:1,payload_ref:null,payload_hash:'d'.repeat(64),status:'received',attempts:0,received_at:iso(1800000000000),processed_at:null,error_code:null,facts:{environment:'Sandbox',bundle_id:BUNDLE,notification_uuid:'cross'}}]),/23514/);
await atomicReject(insert('listing_promotion_entitlements',[{...p.entitlements[0],id:uuid(),environment:'Xcode',provider_reference:uuid()}]),/23503|23514/);
const s=await read();for(const environment of ['Production','Xcode']){const bad=structuredClone(s.state);bad.buyers[0].environment=environment;await assert.rejects(repo.compareAndSwap(s.version,bad),/ENVIRONMENT_DISABLED/);}assert.equal(await sql("select count(*) from apple_transactions where environment='Production'"),'1');});
await test('pure projection from persisted entitlement does not modify legacy rows',async()=>{const {resolveEffectivePromotion}=await import('../../supabase/functions/_shared/apple/projection.mjs');const f=await ready(true),s=await read(),l=s.state.listings[0],e=s.state.entitlements[0];const before=await sql('select json_agg(t) from business_submissions t');const premium={...e,plan:'premium',valid_until:iso(f.now()+10000)};const comp={...e,provider:'comp',source_priority:999};assert.equal(resolveEffectivePromotion(l,[premium,comp],'Sandbox',f.now()).plan,'premium');const r=resolveEffectivePromotion(l,[premium,{...e,provider:'stripe'}],'Sandbox',f.now());assert.deepEqual(r.conflicts,['MULTIPLE_PAID_ENTITLEMENTS']);assert.equal(r.valid_until,premium.valid_until);assert.equal(resolveEffectivePromotion({...l,status:'hidden'},[premium],'Sandbox',f.now()).visible,false);assert.equal(resolveEffectivePromotion(l,[premium],'Production',f.now()).plan,'free');assert.equal(await sql('select json_agg(t) from business_submissions t'),before);});
await test('transaction buyer and entitlement assignment cannot be forged through CAS',async()=>{await ready(true);let s=await read();const other={...s.state.buyers[0],id:uuid(),app_account_token:uuid(),app_transaction_id:'TEST-OTHER'};s.state.buyers.push(other);assert.ok(await repo.compareAndSwap(s.version,s.state));s=await read();let bad=structuredClone(s.state);bad.transactions.push({...bad.transactions[0],transaction_id:'989898',app_account_token:other.app_account_token,app_transaction_id:other.app_transaction_id});await assert.rejects(repo.compareAndSwap(s.version,bad),/23503|TRANSACTION_BUYER/);assert.deepEqual(await read(),s);bad=structuredClone(s.state);bad.entitlements.push({...bad.entitlements[0],id:uuid(),provider_reference:uuid()});await assert.rejects(repo.compareAndSwap(s.version,bad),/23503|ENTITLEMENT_ASSIGNMENT/);assert.deepEqual(await read(),s);});
await test('RLS itself filters reads and blocks insert with temporary grants rolled back',async()=>{await ready(true);for(const r of ['anon','authenticated']){assert.equal(await sql(`begin; grant select on apple_buyers to ${r}; set role ${r}; select count(*) from apple_buyers; rollback;`),'0');await assert.rejects(sql(`begin; grant insert on apple_buyers to ${r}; set role ${r}; insert into apple_buyers(bundle_id,environment,status) values('${BUNDLE}','Sandbox','provisional'); rollback;`),/row-level security/);}assert.equal((await read()).state.buyers.length,1);});
await test('rollback specifically after new intent and new slot insert',async()=>{const f=await ready();const before=await read();await f.backend.prepare(f.token,f.list);const reserved=await read();await install(true);await seed(before.state);const initial=await read();for(const t of ['apple_purchase_intents','apple_slot_occupancies']){await assert.rejects(sql(`begin; create function phase39_insert_fault() returns trigger language plpgsql as $$ begin raise exception 'PHASE39_AFTER_INSERT'; end $$; create trigger phase39_insert_fault after insert on ${t} for each row execute function phase39_insert_fault(); select apple_ledger_compare_and_swap(${initial.version},${q(JSON.stringify(reserved.state))}); commit;`),/PHASE39_AFTER_INSERT/);assert.deepEqual(await read(),initial);}assert.ok(await repo.compareAndSwap(initial.version,reserved.state));assert.equal((await read()).state.intents.length,1);assert.equal((await read()).state.slots.length,1);});
await test('SQL catalogue product/plan/slot constraints and notification UUID replay conflict',async()=>{const f=await ready();await f.backend.prepare(f.token,f.list);const s=await read();for(const change of [{slot_number:2},{requested_plan:'premium'},{product_id:'forged'},{buyer_id:uuid()}]){const bad=structuredClone(s.state);bad.intents.push({...bad.intents[0],id:uuid(),idempotency_key:uuid(),...change});await assert.rejects(repo.compareAndSwap(s.version,bad),/23503|23514/);assert.deepEqual(await read(),s);}f.p=await purchase(f,await listing(f));await f.backend.verify(f.token,f.p.input);const e=event(f,'SUBSCRIBED');await f.backend.notification(f.verifier.register(e));await assert.rejects(f.backend.notification(f.verifier.register({...e,notification_type:'REFUND'})),/NOTIFICATION_REPLAY_CONFLICT/);assert.equal((await read()).state.notifications.length,1);});
await test('final clean recreation and essential smoke',async()=>{await install(true);assert.equal((await read()).version,0);assert.equal((await read()).state.catalog.length,20);assert.equal(await sql("select count(*) from apple_product_catalog where enabled"),'0');for(const role of ['anon','authenticated','service_role'])await denied('select * from apple_buyers',role);assert.equal(await sql("select count(*) from pg_class where relnamespace='public'::regnamespace and relkind='r' and relrowsecurity"),'15');assert.equal(await sql('select count(*) from apple_transactions'),'0');});
console.log('TOTAL',results.length,'PASS',results.filter(x=>x.status==='pass').length,'FAIL',results.filter(x=>x.status==='fail').length);

}
main().catch(e=>{console.error(e.stack);process.exitCode=1;});
