import test from 'node:test';import assert from 'node:assert/strict';import {randomBytes} from 'node:crypto';
import {integration} from './node-integration-fixtures.mjs';
import {LocalKeyRing,withLocalRotation} from '/Users/yanier/Documents/abilene-apple-verifier/src/rotation.mjs';
import {authenticate,signRequest} from '/Users/yanier/Documents/abilene-apple-verifier/src/request-auth.mjs';
import {signResponse} from '/Users/yanier/Documents/abilene-apple-verifier/src/response-auth.mjs';
import {NodeAppleVerifierClient} from '../../supabase/functions/_shared/apple/node-verifier-client.mjs';
async function setup(){const f=await integration(),now=f.now();const ring=prefix=>new LocalKeyRing({clock:f.now,current:{id:prefix+'-v2',key:randomBytes(32),notBefore:now-1,notAfter:now+120000},previous:{id:prefix+'-v1',key:randomBytes(32),notBefore:now-60000,notAfter:now+1000}});const requests=ring('request'),responses=ring('response');return {f,requests,responses,c:withLocalRotation(f.config,requests,responses)};}
for(const id of ['request-v2','request-v1'])test('request rotation accepts '+id,async()=>{const {f,requests,c}=await setup();const body=Buffer.from(JSON.stringify(Object.fromEntries(Object.entries({transactionJws:f.purchase.input.transaction_jws,appTransactionJws:f.purchase.input.app_transaction_jws,purchaseIntentId:f.purchase.input.purchase_intent_id,policyId:'sandbox-featured-v1'}).sort())));assert.ok(await authenticate(c,signRequest({...c,requestKeyId:id,requestKey:requests.resolve(id)},body)));});
for(const scenario of ['unknown','expired','tamper'])test('request rotation rejects '+scenario,async()=>{const {f,requests,c}=await setup();const body=Buffer.from('{}'),cfg={...c,requestKeyId:'request-v1',requestKey:requests.resolve('request-v1')};let r=signRequest(cfg,body);if(scenario==='unknown')r=signRequest({...cfg,requestKeyId:'unknown'},body);if(scenario==='expired')f.advance(1000);if(scenario==='tamper')r={...r,body:Buffer.from('{"x":1}')};await assert.rejects(authenticate(c,r));});
for(const scenario of ['current','previous','unknown','expired','tamper'])test('response rotation '+scenario,async()=>{const {f,responses}=await setup();const id=scenario==='current'?'response-v2':'response-v1';const key=responses.resolve(id);f.hooks.alterResult=r=>{const claims=JSON.parse(r.body);const signed=signResponse({...f.config,responseKeyId:scenario==='unknown'?'unknown':id,responseKey:key},claims);if(scenario==='expired')f.advance(1000);return {...signed,httpStatus:200,...(scenario==='tamper'?{signature:'0'.repeat(64)}:{})};};f.backend.appleVerifier=new NodeAppleVerifierClient({requestKey:f.config.requestKey,responseKey:responses.entries[0].key,responseKeys:responses,exchange:f.exchange,clock:f.now});if(['current','previous'].includes(scenario))assert.equal((await f.verify()).status,'delivered');else{await assert.rejects(f.verify());assert.equal(f.store.state.deliveries.length,0);}});
test('rotation rejects request/response secret reuse',async()=>{const {f,requests}=await setup();assert.throws(()=>withLocalRotation(f.config,requests,requests));});
test('expired key cannot return through observed clock rollback',async()=>{const {f,requests}=await setup();f.advance(1000);assert.throws(()=>requests.resolve('request-v1'));f.advance(-1000);assert.throws(()=>requests.resolve('request-v1'));});
