import test from 'node:test';import assert from 'node:assert/strict';
import {composeProduction} from '../../supabase/functions/_shared/apple/production/composition.mjs';
import {setup} from './fixtures.mjs';
import {installationKey} from '../../supabase/functions/_shared/apple/production/identity.mjs';
import {sha256} from '../../supabase/functions/_shared/apple/domain.mjs';
import {verifyProductionAck,ACK_BINDINGS} from '../../supabase/functions/_shared/apple/production/ack.mjs';
async function fixture(plan='featured'){
 const f=await setup(),token=await f.buyer(),list=await f.listing(token);list.requested_plan=plan;
 for(const rows of Object.values(f.store.state))if(Array.isArray(rows))for(const r of rows)if(r.environment)r.environment='Production';
 f.store.state.catalog=f.store.state.catalog.filter(p=>p.slot_number===1);for(const p of f.store.state.catalog)p.subscription_group_id='22382531';
 const install=f.store.state.installations[0],buyer=f.store.state.buyers[0];buyer.app_transaction_id='112001';
 const signing=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),key=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);
 const spki=Buffer.from(await crypto.subtle.exportKey('spki',key.publicKey)).toString('base64'),keyid=(await installationKey(spki)).id;install.key_id=keyid;
 const user={id:crypto.randomUUID()},seen=new Set(),evidence=new Map();
 const db={rpc:async(name,args)=>{if(name==='apple_consume_installation_nonce'){if(seen.has(args.p_nonce))throw Error('REPLAY');seen.add(args.p_nonce);return true;}if(name==='apple_ledger_snapshot_production')return f.store.read();if(name.startsWith('apple_ledger_compare_and_swap'))return f.store.compareAndSwap(args.expected_version,args.next_state);throw Error('MOCK_RPC_UNSUPPORTED');},installation:async id=>id===keyid?{key_id:keyid,public_spki:spki,user_id:user.id,installation_id:install.installation_id}:null};
 const composition=await composeProduction({db,auth:async jwt=>jwt==='AUTHENTICATED_TEST_SESSION'?user:null,clock:f.now,kid:'production-http-fixture',ackPrivate:await crypto.subtle.exportKey('pkcs8',signing.privateKey),verifier:{verifyTransaction:async id=>{if(!evidence.has(id))throw Error('UNVERIFIED');return evidence.get(id);}}});
 async function call(action,payload,{auth=true,mutate}={}){const payload_text=JSON.stringify({capability:token,...payload}),nonce=crypto.randomUUID(),issued_at=Date.now(),message=JSON.stringify(['apple-request-v1',action,nonce,String(issued_at),await sha256(payload_text)]);const input={payload_text,key_id:keyid,nonce,issued_at,signature:Buffer.from(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},key.privateKey,new TextEncoder().encode(message))).toString('base64')};mutate?.(input);return composition.handle(new Request('https://example.invalid/apple-iap',{method:'POST',headers:{authorization:'Bearer '+(auth?'AUTHENTICATED_TEST_SESSION':'WRONG')},body:JSON.stringify({action,input})}));}
 // Request authentication clock is real while the deterministic domain ledger uses fixture time.
 composition.identity.clock=Date.now;
 return {...f,token,list,install,buyer,evidence,signing,composition,call};
}
for(const plan of ['featured','premium'])test('production HTTP '+plan+' start→verify→durable ACK→lost response recovery',async()=>{const f=await fixture(plan),p=await f.call('prepare',f.list);assert.equal(p.status,200);const intent=await p.json();assert.equal((await f.call('start',{purchase_intent_id:intent.purchase_intent_id})).status,200);const t={bundle_id:'com.abilenevibes.app',environment:'Production',transaction_id:'112007',original_transaction_id:'112007',product_id:intent.product_id,app_account_token:f.buyer.app_account_token,app_transaction_id:f.buyer.app_transaction_id,subscription_group_id:'22382531',purchase_date:new Date(f.now()).toISOString(),expires_date:new Date(f.now()+86400000).toISOString(),revocation_date:null,revocation_reason:null,ownership_type:'PURCHASED',is_upgraded:false};f.evidence.set('VERIFIED_MOCK',t);const input={purchase_intent_id:intent.purchase_intent_id,transaction_jws:'VERIFIED_MOCK',app_transaction_jws:'APP_MOCK',idempotency_key:f.list.idempotency_key};const result=await (await f.call('verify',input)).json();assert.equal(result.status,'delivered');assert.equal(f.store.state.deliveries.length,1);const claims=JSON.parse(Buffer.from(result.confirmation.signed_jws.split('.')[1],'base64url'));const expected=Object.fromEntries(ACK_BINDINGS.map(k=>[k,claims[k]]));expected.installation_id=f.install.installation_id;expected.productId=t.product_id;expected.transactionId=t.transaction_id;assert.equal((await verifyProductionAck(result.confirmation,expected,{keys:{'production-http-fixture':f.signing.publicKey},now:Math.floor(f.now()/1000)})).finishAllowed,true);assert.equal((await (await f.call('recover',input)).json()).status,'already_delivered');assert.equal(f.store.state.deliveries.length,1);});
test('production HTTP rejects invalid Supabase session before reservation',async()=>{const f=await fixture();assert.equal((await f.call('prepare',f.list,{auth:false})).status,401);assert.equal(f.store.state.intents.length,0);});
test('production HTTP rejects tampered signed payload before reservation',async()=>{const f=await fixture();assert.equal((await f.call('prepare',f.list,{mutate:i=>i.payload_text+=' '})).status,401);assert.equal(f.store.state.intents.length,0);});
test('production HTTP refuses missing installation',async()=>{const f=await fixture();assert.equal((await f.call('prepare',f.list,{mutate:i=>i.key_id='unknown'})).status,401);});
test('production HTTP rejects oversized body',async()=>{const f=await fixture();assert.equal((await f.composition.handle(new Request('https://example.invalid',{method:'POST',body:' '.repeat(262145)}))).status,413);});
