import test from 'node:test';import assert from 'node:assert/strict';
import {ProductionIdentity,installationKey} from '../../supabase/functions/_shared/apple/production/identity.mjs';
import {sha256} from '../../supabase/functions/_shared/apple/domain.mjs';
const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),spki=Buffer.from(await crypto.subtle.exportKey('spki',pair.publicKey)).toString('base64'),keyID=(await installationKey(spki)).id,now=Date.now(),user={id:crypto.randomUUID()};
const sign=async message=>Buffer.from(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},pair.privateKey,new TextEncoder().encode(JSON.stringify(message)))).toString('base64');
function fixture(){const c={id:crypto.randomUUID(),user_id:user.id,nonce:crypto.randomUUID(),public_spki:spki,expires_at:new Date(now+60000).toISOString()},key={key_id:keyID,user_id:user.id,public_spki:spki,installation_id:crypto.randomUUID()},calls=[],seen=new Set();let verifies=0;const db={challenge:async()=>c,installation:async()=>key,rpc:async(name,args)=>{calls.push(name);if(name==='apple_consume_installation_nonce'){if(seen.has(args.p_nonce))throw Error('REPLAY');seen.add(args.p_nonce);}return {safe:'fixture'};}};const identity=new ProductionIdentity({db,clock:()=>now,verifier:{verifyAppTransaction:async()=>{verifies++;return {app_transaction_id:'112',notAfter:now+15000};}}});return {c,key,calls,identity,verifies:()=>verifies};}
async function request(action='prepare'){const payload_text=JSON.stringify({capability:'MOCK',listing_id:crypto.randomUUID()}),nonce=crypto.randomUUID(),issued_at=now;return {key_id:keyID,payload_text,nonce,issued_at,signature:await sign(['apple-request-v1',action,nonce,String(issued_at),await sha256(payload_text)])};}
test('installation proof verifies the exact authenticated request and consumes nonce',async()=>{const f=fixture();assert.equal((await f.identity.request(user,'prepare',await request())).installation.key_id,keyID);assert.deepEqual(f.calls,['apple_consume_installation_nonce']);});
for(const field of ['signature','payload_text','nonce','issued_at'])test('installation rejects tampered '+field,async()=>{const f=fixture(),r=await request();r[field]=field==='issued_at'?now+1:field==='signature'?'AA==':r[field]+'x';await assert.rejects(f.identity.request(user,'prepare',r));assert.equal(f.calls.length,0);});
for(const mode of ['wrong-user','revoked','wrong-key','missing'])test('installation rejects '+mode,async()=>{const f=fixture();if(mode==='revoked')f.key.revoked_at=new Date().toISOString();if(mode==='wrong-key')f.key.public_spki='AA==';if(mode==='missing')delete f.key.public_spki;await assert.rejects(f.identity.request(mode==='wrong-user'?{id:'other'}:user,'prepare',await request()));assert.equal(f.calls.length,0);});
test('installation signature cannot move between actions',async()=>{const f=fixture();await assert.rejects(f.identity.request(user,'verify',await request('prepare')));});
test('installation duplicate nonce rejected durably',async()=>{const f=fixture(),r=await request();await f.identity.request(user,'prepare',r);await assert.rejects(f.identity.request(user,'prepare',r));});
async function completion(f){const input={challenge_id:f.c.id,listing_type:'business',listing_id:crypto.randomUUID(),app_transaction_jws:'MOCK_ONLY'};input.signature=await sign(['apple-bootstrap-v1',f.c.id,f.c.nonce,input.listing_type,input.listing_id,await sha256(input.app_transaction_jws)]);return input;}
test('bootstrap proves key and app before atomic ownership transaction',async()=>{const f=fixture();await f.identity.complete(user,await completion(f));assert.equal(f.verifies(),1);assert.deepEqual(f.calls,['apple_bootstrap_complete']);});
for(const mode of ['other-user','expired','consumed','wrong-listing','wrong-app'])test('bootstrap rejects '+mode,async()=>{const f=fixture(),r=await completion(f);if(mode==='expired')f.c.expires_at=new Date(now-1).toISOString();if(mode==='consumed')f.c.consumed_at=new Date(now).toISOString();if(mode==='wrong-listing')r.listing_id=crypto.randomUUID();if(mode==='wrong-app')r.app_transaction_jws='OTHER';await assert.rejects(f.identity.complete(mode==='other-user'?{id:'other'}:user,r));assert.equal(f.calls.length,0);});
