import test from 'node:test';import assert from 'node:assert/strict';
import {expiredFixture} from './expired-recovery-fixtures.mjs';
import {AppleError} from '../../supabase/functions/_shared/apple/domain.mjs';
import {observer} from '../../supabase/functions/_shared/apple/safe-observability.mjs';
for(const code of ['NODE_UNAVAILABLE','NODE_TIMEOUT','NODE_AUTH_FAILED','NODE_RESPONSE_EXPIRED','NODE_INVALID_CONTRACT'])test('observable recovery failure '+code,async()=>{const f=await expiredFixture();f.backend.appleVerifier.verifyTransaction=async()=>{throw new AppleError(code);};await assert.rejects(f.recover(),e=>e.code===code);assert.equal(f.store.state.expired_purchases.length,0);assert.equal(f.store.state.deliveries.length,0);assert.ok(f.events.some(x=>x.outcome==='FAIL'&&x.safeCode===code));});
for(const name of ['DB failure','CAS exhaustion','rollback'])test('observable '+name,async()=>{const f=await expiredFixture();if(name==='DB failure')f.store.compareAndSwap=async()=>{throw new AppleError('LEDGER_COMMIT_FAILED');};else if(name==='CAS exhaustion')f.store.compareAndSwap=async()=>false;else f.store.crashBefore=true;await assert.rejects(f.recover());assert.equal(f.store.state.expired_purchases.length,0);assert.equal(f.store.state.challenges.length,0);assert.ok(f.events.some(x=>x.stage==='CAS'||x.safeCode==='ROLLBACK'));});
test('ACK failure keeps durable active delivery but never grants finish; authorized retry recovers',async()=>{const f=await expiredFixture({active:true}),sign=f.backend.signer.sign.bind(f.backend.signer);f.backend.signer.sign=async()=>{throw new AppleError('ACK_SIGN_FAILED');};await assert.rejects(f.recover());assert.equal(f.store.state.deliveries.length,1);assert.ok(f.events.some(x=>x.stage==='ACK'&&x.outcome==='FAIL'));f.backend.signer.sign=sign;const result=await f.recover();assert.equal(result.status,'already_delivered');assert.equal(f.store.state.deliveries.length,1);});
test('closed logger drops arbitrary sensitive metadata and sink errors',()=>{const rows=[],emit=observer(x=>rows.push(x));emit('JWS.SECRET','FAIL','SECRET',{token:'SECRET',raw:'SECRET',httpStatus:409});assert.ok(!rows.join('').includes('SECRET'));assert.doesNotThrow(()=>observer(()=>{throw Error('sink');})('DB'));});
test('lost commit response is logged UNKNOWN rather than false rollback',async()=>{const f=await expiredFixture();f.store.crashAfter=true;await assert.rejects(f.recover());assert.equal(f.store.state.expired_purchases.length,1);assert.ok(f.events.some(x=>x.safeCode==='COMMIT_UNKNOWN'));assert.ok(!f.events.some(x=>x.safeCode==='ROLLBACK'));});
